insert into public.brand_table (name) values ('Back to Nature');
insert into public.brand_table (name) values ('Bond Bread');
insert into public.brand_table (name) values ('Bost''s Bread');
insert into public.brand_table (name) values ('Burry''s');
insert into public.brand_table (name) values ('Cobblestone');
insert into public.brand_table (name) values ('Dave''s Killer Bread');
insert into public.brand_table (name) values ('Davidovich Bagels');
insert into public.brand_table (name) values ('Entenmann''s');
insert into public.brand_table (name) values ('Holsum Bread');
insert into public.brand_table (name) values ('Home Pride');
insert into public.brand_table (name) values ('Hovis');
insert into public.brand_table (name) values ('King''s Hawaiian');
insert into public.brand_table (name) values ('Kits');
insert into public.brand_table (name) values ('Lender''s Bagels');
insert into public.brand_table (name) values ('McVitie''s');
insert into public.brand_table (name) values ('Merita Breads');
insert into public.brand_table (name) values ('Mother''s Pride');
insert into public.brand_table (name) values ('Nabisco');
insert into public.brand_table (name) values ('Nature''s Own');
insert into public.brand_table (name) values ('Newman''s Own');
insert into public.brand_table (name) values ('Pepperidge Farm');
insert into public.brand_table (name) values ('Polarbröd');
insert into public.brand_table (name) values ('Roman Meal');
insert into public.brand_table (name) values ('Sunbeam Bread');
insert into public.brand_table (name) values ('Tastykake');
insert into public.brand_table (name) values ('Thomas');
insert into public.brand_table (name) values ('Warburtons');
insert into public.brand_table (name) values ('Westminster Cracker Company');
insert into public.brand_table (name) values ('Wonder Bread');
insert into public.brand_table (name) values ('Arrowhead Mills');
insert into public.brand_table (name) values ('Atkins Nutritionals');
insert into public.brand_table (name) values ('Aunt Jemima');
insert into public.brand_table (name) values ('Betty Crocker');
insert into public.brand_table (name) values ('Bisquick[');
insert into public.brand_table (name) values ('Bob''s Red Mill');
insert into public.brand_table (name) values ('Boulder Brands');
insert into public.brand_table (name) values ('Cherrybrook Kitchen');
insert into public.brand_table (name) values ('Dassant');
insert into public.brand_table (name) values ('Jack & Jason''s Pancakes & Waffles');
insert into public.brand_table (name) values ('Jiffy mix');
insert into public.brand_table (name) values ('King Arthur Baking');
insert into public.brand_table (name) values ('Kodiak Cakes');
insert into public.brand_table (name) values ('Krusteaz');
insert into public.brand_table (name) values ('Martha White');
insert into public.brand_table (name) values ('Mrs. Butterworth''s');
insert into public.brand_table (name) values ('Dr. Oetker');
insert into public.brand_table (name) values ('Pillsbury');
insert into public.brand_table (name) values ('Ralcorp');
insert into public.brand_table (name) values ('Streit''s');
insert into public.brand_table (name) values ('Akta-Vite');
insert into public.brand_table (name) values ('Almdudler');
insert into public.brand_table (name) values ('Alpro');
insert into public.brand_table (name) values ('Apple Sidra');
insert into public.brand_table (name) values ('Artos');
insert into public.brand_table (name) values ('Asia');
insert into public.brand_table (name) values ('Banana Flavored Milk');
insert into public.brand_table (name) values ('Banania');
insert into public.brand_table (name) values ('Barleycup');
insert into public.brand_table (name) values ('Baron von Lemon');
insert into public.brand_table (name) values ('Boga');
insert into public.brand_table (name) values ('Bournvita');
insert into public.brand_table (name) values ('Bovril');
insert into public.brand_table (name) values ('Carnation');
insert into public.brand_table (name) values ('Caro');
insert into public.brand_table (name) values ('Clamato');
insert into public.brand_table (name) values ('Clipper Teas');
insert into public.brand_table (name) values ('Club-Mate');
insert into public.brand_table (name) values ('Cocio');
insert into public.brand_table (name) values ('Cool Mountain Beverages');
insert into public.brand_table (name) values ('Cravendale');
insert into public.brand_table (name) values ('Crystal Light');
insert into public.brand_table (name) values ('Danone');
insert into public.brand_table (name) values ('Double Seven');
insert into public.brand_table (name) values ('El Namroud');
insert into public.brand_table (name) values ('Energen');
insert into public.brand_table (name) values ('Frugo');
insert into public.brand_table (name) values ('Gold Spot');
insert into public.brand_table (name) values ('Goombay Punch');
insert into public.brand_table (name) values ('Höpt');
insert into public.brand_table (name) values ('Horlicks');
insert into public.brand_table (name) values ('Jūrokucha');
insert into public.brand_table (name) values ('Juven');
insert into public.brand_table (name) values ('Kalleh Dairy');
insert into public.brand_table (name) values ('Killer Shake');
insert into public.brand_table (name) values ('Kinnie');
insert into public.brand_table (name) values ('Kinohimitsu');
insert into public.brand_table (name) values ('Maltos-Cannabis');
insert into public.brand_table (name) values ('Manhattan Special');
insert into public.brand_table (name) values ('Maxwell House International');
insert into public.brand_table (name) values ('Mercy');
insert into public.brand_table (name) values ('Nestlé Milo');
insert into public.brand_table (name) values ('MiO');
insert into public.brand_table (name) values ('Mirinda');
insert into public.brand_table (name) values ('Mr Sherick''s Shakes');
insert into public.brand_table (name) values ('Nescafé');
insert into public.brand_table (name) values ('Nespresso');
insert into public.brand_table (name) values ('Nesquik');
insert into public.brand_table (name) values ('Nestea');
insert into public.brand_table (name) values ('Nestlé');
insert into public.brand_table (name) values ('Nexcite');
insert into public.brand_table (name) values ('Nutrimato');
insert into public.brand_table (name) values ('Ovaltine');
insert into public.brand_table (name) values ('PDQ Chocolate');
insert into public.brand_table (name) values ('PJ''s Smoothies');
insert into public.brand_table (name) values ('Pog');
insert into public.brand_table (name) values ('POM Wonderful');
insert into public.brand_table (name) values ('Postum');
insert into public.brand_table (name) values ('Silk');
insert into public.brand_table (name) values ('Sinalco');
insert into public.brand_table (name) values ('Swiss Miss');
insert into public.brand_table (name) values ('Vitamalt');
insert into public.brand_table (name) values ('Vitamin Water');
insert into public.brand_table (name) values ('Wander AG');
insert into public.brand_table (name) values ('Welch''s');
insert into public.brand_table (name) values ('Wyler''s');
insert into public.brand_table (name) values ('Yop');
insert into public.brand_table (name) values ('Zarex');
insert into public.brand_table (name) values ('Afri-Cola');
insert into public.brand_table (name) values ('Coca-Cola');
insert into public.brand_table (name) values ('Pepsi');
insert into public.brand_table (name) values ('Abbey Crunch');
insert into public.brand_table (name) values ('Aero Biscuits');
insert into public.brand_table (name) values ('Afghan');
insert into public.brand_table (name) values ('Afternoon Tea');
insert into public.brand_table (name) values ('Arnott');
insert into public.brand_table (name) values ('Biscuit rose de Reims');
insert into public.brand_table (name) values ('Biscuits Fossier');
insert into public.brand_table (name) values ('Blue Riband');
insert into public.brand_table (name) values ('BN');
insert into public.brand_table (name) values ('Breakaway');
insert into public.brand_table (name) values ('Britannia Biscuits');
insert into public.brand_table (name) values ('Burton''s');
insert into public.brand_table (name) values ('Cadbury Caramel Crunch');
insert into public.brand_table (name) values ('Cadbury Fingers');
insert into public.brand_table (name) values ('Cadbury Snack');
insert into public.brand_table (name) values ('Cadbury Snaps');
insert into public.brand_table (name) values ('Cameo Creme');
insert into public.brand_table (name) values ('Carr''s');
insert into public.brand_table (name) values ('CBL Munchee Bangladesh');
insert into public.brand_table (name) values ('Ceylon Biscuits Limited');
insert into public.brand_table (name) values ('Cheddars');
insert into public.brand_table (name) values ('Chips Ahoy!');
insert into public.brand_table (name) values ('Club');
insert into public.brand_table (name) values ('Club Milk');
insert into public.brand_table (name) values ('DeMet''s Candy Company');
insert into public.brand_table (name) values ('Domino');
insert into public.brand_table (name) values ('Drifter');
insert into public.brand_table (name) values ('Famous Amos');
insert into public.brand_table (name) values ('Kinder');
insert into public.brand_table (name) values ('Filipinos');
insert into public.brand_table (name) values ('Fox''s Biscuits');
insert into public.brand_table (name) values ('Galletas Fontaneda');
insert into public.brand_table (name) values ('Galletas Gullón');
insert into public.brand_table (name) values ('Gold');
insert into public.brand_table (name) values ('Happy Faces');
insert into public.brand_table (name) values ('Hello Panda');
insert into public.brand_table (name) values ('Hobnob biscuit');
insert into public.brand_table (name) values ('HobNob');
insert into public.brand_table (name) values ('Hovis biscuit');
insert into public.brand_table (name) values ('Hula Hoops');
insert into public.brand_table (name) values ('Huntley & Palmers');
insert into public.brand_table (name) values ('Iced VoVo');
insert into public.brand_table (name) values ('Jacob''s');
insert into public.brand_table (name) values ('Jaffa Cakes');
insert into public.brand_table (name) values ('Jammie Dodgers');
insert into public.brand_table (name) values ('Kägi Söhne');
insert into public.brand_table (name) values ('Kambly');
insert into public.brand_table (name) values ('Kingston');
insert into public.brand_table (name) values ('Kit Kat');
insert into public.brand_table (name) values ('Kits');
insert into public.brand_table (name) values ('KP Snacks');
insert into public.brand_table (name) values ('Krispie');
insert into public.brand_table (name) values ('Leibniz-Keks');
insert into public.brand_table (name) values ('Loacker');
insert into public.brand_table (name) values ('Lotus Bakeries');
insert into public.brand_table (name) values ('LU');
insert into public.brand_table (name) values ('Maliban');
insert into public.brand_table (name) values ('McCoy''s');
insert into public.brand_table (name) values ('McVitie''s');
insert into public.brand_table (name) values ('Meanie');
insert into public.brand_table (name) values ('Monte Carlo');
insert into public.brand_table (name) values ('Neapolitan wafer');
insert into public.brand_table (name) values ('Newman''s Own');
insert into public.brand_table (name) values ('Nik Naks (British snack)');
insert into public.brand_table (name) values ('Oreo');
insert into public.brand_table (name) values ('Parle-G');
insert into public.brand_table (name) values ('Peek Freans');
insert into public.brand_table (name) values ('Penguin (biscuit)');
insert into public.brand_table (name) values ('Pirouline');
insert into public.brand_table (name) values ('Plasmon biscuit');
insert into public.brand_table (name) values ('Quadratini');
insert into public.brand_table (name) values ('Quely');
insert into public.brand_table (name) values ('Skips');
insert into public.brand_table (name) values ('Space Raiders');
insert into public.brand_table (name) values ('Sunshine Biscuits');
insert into public.brand_table (name) values ('Taxi');
insert into public.brand_table (name) values ('Tim Tam');
insert into public.brand_table (name) values ('Tiny Teddy');
insert into public.brand_table (name) values ('Tracker');
insert into public.brand_table (name) values ('Trio');
insert into public.brand_table (name) values ('Tunnock''s wafer');
insert into public.brand_table (name) values ('Tunnock''s');
insert into public.brand_table (name) values ('Twiglets');
insert into public.brand_table (name) values ('Twix');
insert into public.brand_table (name) values ('United Biscuits');
insert into public.brand_table (name) values ('Vienna Fingers');
insert into public.brand_table (name) values ('Wagon Wheels');
insert into public.brand_table (name) values ('Waitrose Duchy Organic');
insert into public.brand_table (name) values ('Walkers Shortbread');
insert into public.brand_table (name) values ('Wheat Crunchies');
insert into public.brand_table (name) values ('Wright''s Biscuits');
insert into public.brand_table (name) values ('Club');
insert into public.brand_table (name) values ('Jacobs Cream Crackers');
insert into public.brand_table (name) values ('Ritz');
insert into public.brand_table (name) values ('Ry-Krisp');
insert into public.brand_table (name) values ('Triscuit');
insert into public.brand_table (name) values ('Wheat Thins');
insert into public.brand_table (name) values ('Balance Bar');
insert into public.brand_table (name) values ('CalorieMate');
insert into public.brand_table (name) values ('Clif Bar');
insert into public.brand_table (name) values ('Lärabar');
insert into public.brand_table (name) values ('LUNA Bar');
insert into public.brand_table (name) values ('PowerBar');
insert into public.brand_table (name) values ('Rxbar');
insert into public.brand_table (name) values ('Soldier Fuel');
insert into public.brand_table (name) values ('Tiger''s Milk');
insert into public.brand_table (name) values ('Cream of Wheat');
insert into public.brand_table (name) values ('Malt-O-Meal');
insert into public.brand_table (name) values ('Maypo');
insert into public.brand_table (name) values ('McCann''s Steel Cut Irish Oatmeal');
insert into public.brand_table (name) values ('Quaker Oats Company');
insert into public.brand_table (name) values ('Scott''s Porage Oats');
insert into public.brand_table (name) values ('Barny Cakes');
insert into public.brand_table (name) values ('Baskin Robbins');
insert into public.brand_table (name) values ('Betty Crocker');
insert into public.brand_table (name) values ('Bumpy cake');
insert into public.brand_table (name) values ('Cadbury Cake Bars');
insert into public.brand_table (name) values ('Cadbury Highlights');
insert into public.brand_table (name) values ('Chocodile Twinkie');
insert into public.brand_table (name) values ('Drake''s Cakes');
insert into public.brand_table (name) values ('Dunkin'' Donuts');
insert into public.brand_table (name) values ('Hostess CupCake');
insert into public.brand_table (name) values ('Ho Hos');
insert into public.brand_table (name) values ('Hostess');
insert into public.brand_table (name) values ('Krispy Kreme');
insert into public.brand_table (name) values ('Mars Muffin');
insert into public.brand_table (name) values ('McVitie''s');
insert into public.brand_table (name) values ('Mr Kipling');
insert into public.brand_table (name) values ('Secret Recipe');
insert into public.brand_table (name) values ('Suzy Q');
insert into public.brand_table (name) values ('Twinkie');
insert into public.brand_table (name) values ('Viennetta');
insert into public.brand_table (name) values ('Yodels');
insert into public.brand_table (name) values ('Zingers');
insert into public.brand_table (name) values ('Ayam Brand');
insert into public.brand_table (name) values ('Bush''s Baked Beans');
insert into public.brand_table (name) values ('Chef Boyardee');
insert into public.brand_table (name) values ('Chicken of the Sea');
insert into public.brand_table (name) values ('Contadina');
insert into public.brand_table (name) values ('Crosse & Blackwell');
insert into public.brand_table (name) values ('Del Monte Foods');
insert into public.brand_table (name) values ('Fray Bentos');
insert into public.brand_table (name) values ('Gerber Singles');
insert into public.brand_table (name) values ('Grandma Brown''s Baked Beans');
insert into public.brand_table (name) values ('Green Giant');
insert into public.brand_table (name) values ('Greenseas');
insert into public.brand_table (name) values ('Heinz');
insert into public.brand_table (name) values ('Hunt''s');
insert into public.brand_table (name) values ('Libby''s');
insert into public.brand_table (name) values ('Manwich');
insert into public.brand_table (name) values ('Prem');
insert into public.brand_table (name) values ('Ro-Tel');
insert into public.brand_table (name) values ('Spam');
insert into public.brand_table (name) values ('StarKist');
insert into public.brand_table (name) values ('Treet');
insert into public.brand_table (name) values ('Van Camp''s');
insert into public.brand_table (name) values ('Wolf Brand Chili');
insert into public.brand_table (name) values ('Andy Capp''s fries');
insert into public.brand_table (name) values ('Barcel');
insert into public.brand_table (name) values ('Brannigans');
insert into public.brand_table (name) values ('Bugles');
insert into public.brand_table (name) values ('Cape Cod Potato Chips');
insert into public.brand_table (name) values ('Cheetos');
insert into public.brand_table (name) values ('Cheez Doodles');
insert into public.brand_table (name) values ('Cheez-It');
insert into public.brand_table (name) values ('Cheezies');
insert into public.brand_table (name) values ('CornNuts');
insert into public.brand_table (name) values ('David Sunflower Seeds');
insert into public.brand_table (name) values ('Doritos');
insert into public.brand_table (name) values ('Frito-Lay');
insert into public.brand_table (name) values ('Fritos');
insert into public.brand_table (name) values ('Golden Wonder');
insert into public.brand_table (name) values ('Hula Hoops');
insert into public.brand_table (name) values ('Kettle Foods');
insert into public.brand_table (name) values ('KP Nuts');
insert into public.brand_table (name) values ('Kurkure');
insert into public.brand_table (name) values ('Lay''s Stax');
insert into public.brand_table (name) values ('McCoys Crisps');
insert into public.brand_table (name) values ('Monster Munch');
insert into public.brand_table (name) values ('Munchos');
insert into public.brand_table (name) values ('Nobby''s Nuts');
insert into public.brand_table (name) values ('Phileas Fogg');
insert into public.brand_table (name) values ('Pirate''s Booty');
insert into public.brand_table (name) values ('Pringles');
insert into public.brand_table (name) values ('Ringos');
insert into public.brand_table (name) values ('Ruffles');
insert into public.brand_table (name) values ('San Nicasio');
insert into public.brand_table (name) values ('Space Raiders');
insert into public.brand_table (name) values ('Sun Chips');
insert into public.brand_table (name) values ('Smith''s Crisps');
insert into public.brand_table (name) values ('The Smith''s Snackfood Company');
insert into public.brand_table (name) values ('Tudor Crisps');
insert into public.brand_table (name) values ('Twiglets');
insert into public.brand_table (name) values ('Twisties');
insert into public.brand_table (name) values ('Tyrrells');
insert into public.brand_table (name) values ('Tyrrells Apple Chips');
insert into public.brand_table (name) values ('Walkers Crisps');
insert into public.brand_table (name) values ('Wheat Crunchies');
insert into public.brand_table (name) values ('Wise Foods');
insert into public.brand_table (name) values ('Wotsits');
insert into public.brand_table (name) values ('almarai');
insert into public.brand_table (name) values ('Amul');
insert into public.brand_table (name) values ('Borden');
insert into public.brand_table (name) values ('Broughton Foods Company');
insert into public.brand_table (name) values ('Chivers');
insert into public.brand_table (name) values ('Eagle Brand');
insert into public.brand_table (name) values ('Garelick Farms');
insert into public.brand_table (name) values ('Horizon Organic');
insert into public.brand_table (name) values ('Iran Dairy Industries Co.');
insert into public.brand_table (name) values ('Louis Trauth Dairy');
insert into public.brand_table (name) values ('Mayfield Dairy');
insert into public.brand_table (name) values ('Meadow Gold Dairies');
insert into public.brand_table (name) values ('Organic Valley');
insert into public.brand_table (name) values ('Purity Dairies');
insert into public.brand_table (name) values ('Reddi-wip');
insert into public.brand_table (name) values ('Selecta');
insert into public.brand_table (name) values ('T. G. Lee Dairy');
insert into public.brand_table (name) values ('Tuscan Dairy Farms');
insert into public.brand_table (name) values ('Alpine Lace');
insert into public.brand_table (name) values ('Borden');
insert into public.brand_table (name) values ('Cheez Whiz');
insert into public.brand_table (name) values ('Easy Cheese');
insert into public.brand_table (name) values ('Eden');
insert into public.brand_table (name) values ('Gossner Foods');
insert into public.brand_table (name) values ('Kraft');
insert into public.brand_table (name) values ('Palmetto Cheese');
insert into public.brand_table (name) values ('Sargento');
insert into public.brand_table (name) values ('Watonga Cheese');
insert into public.brand_table (name) values ('Velveeta');
insert into public.brand_table (name) values ('Egg Beaters');
insert into public.brand_table (name) values ('Banquet');
insert into public.brand_table (name) values ('Birds Eye');
insert into public.brand_table (name) values ('Findus');
insert into public.brand_table (name) values ('Freezer Queen');
insert into public.brand_table (name) values ('FRoSTA');
insert into public.brand_table (name) values ('Jus-Rol');
insert into public.brand_table (name) values ('Marie Callender''s');
insert into public.brand_table (name) values ('Stouffer''s');
insert into public.brand_table (name) values ('Tombstone');
insert into public.brand_table (name) values ('XLNT Foods');
insert into public.brand_table (name) values ('Ambrosia');
insert into public.brand_table (name) values ('Angel Delight');
insert into public.brand_table (name) values ('Ben & Jerry''s');
insert into public.brand_table (name) values ('Bird''s Custard');
insert into public.brand_table (name) values ('Bounty ice cream');
insert into public.brand_table (name) values ('Eskimo');
insert into public.brand_table (name) values ('Gü');
insert into public.brand_table (name) values ('Häagen-Dazs');
insert into public.brand_table (name) values ('Keventers Milkshake');
insert into public.brand_table (name) values ('Magnolia');
insert into public.brand_table (name) values ('Magnum');
insert into public.brand_table (name) values ('Müller Rice');
insert into public.brand_table (name) values ('Selecta');
insert into public.brand_table (name) values ('Solero');
insert into public.brand_table (name) values ('Wall''s ');
insert into public.brand_table (name) values ('Armour & Company');
insert into public.brand_table (name) values ('Butterball');
insert into public.brand_table (name) values ('Columbus Craft Meats');
insert into public.brand_table (name) values ('Frank ''n Stuff');
insert into public.brand_table (name) values ('Gorton''s of Gloucester');
insert into public.brand_table (name) values ('Gwaltney');
insert into public.brand_table (name) values ('Hebrew National');
insert into public.brand_table (name) values ('Hormel');
insert into public.brand_table (name) values ('Jennie-O');
insert into public.brand_table (name) values ('Jimmy Dean');
insert into public.brand_table (name) values ('Libby''s');
insert into public.brand_table (name) values ('Omaha Steaks');
insert into public.brand_table (name) values ('Oscar Mayer');
insert into public.brand_table (name) values ('Spam');
insert into public.brand_table (name) values ('Wall''s sausages');
insert into public.brand_table (name) values ('Becel');
insert into public.brand_table (name) values ('Bertolli');
insert into public.brand_table (name) values ('Blue Bonnet');
insert into public.brand_table (name) values ('Country Crock');
insert into public.brand_table (name) values ('Crisco');
insert into public.brand_table (name) values ('Flora');
insert into public.brand_table (name) values ('I Can''t Believe It''s Not Butter!');
insert into public.brand_table (name) values ('Imperial Margarine');
insert into public.brand_table (name) values ('Lambda');
insert into public.brand_table (name) values ('Land O''Lakes');
insert into public.brand_table (name) values ('PAM');
insert into public.brand_table (name) values ('Parkay');
insert into public.brand_table (name) values ('Rafhan');
insert into public.brand_table (name) values ('Sana');
insert into public.brand_table (name) values ('Spry Vegetable Shortening');
insert into public.brand_table (name) values ('Stork');
insert into public.brand_table (name) values ('Wesson cooking oil');
insert into public.brand_table (name) values ('Branston');
insert into public.brand_table (name) values ('Crosse & Blackwell');
insert into public.brand_table (name) values ('Sarson''s');
insert into public.brand_table (name) values ('Datu Puti');
insert into public.brand_table (name) values ('Haywards');
insert into public.brand_table (name) values ('Maille');
insert into public.brand_table (name) values ('Mt. Olive');
insert into public.brand_table (name) values ('Vlasic Pickles');
insert into public.brand_table (name) values ('Buddy Fruits');
insert into public.brand_table (name) values ('Buitoni');
insert into public.brand_table (name) values ('Candwich');
insert into public.brand_table (name) values ('Conimex');
insert into public.brand_table (name) values ('Continental');
insert into public.brand_table (name) values ('DiGiorno');
insert into public.brand_table (name) values ('Findus');
insert into public.brand_table (name) values ('Gardein');
insert into public.brand_table (name) values ('Gardenburger');
insert into public.brand_table (name) values ('Gerber');
insert into public.brand_table (name) values ('Healthy Choice');
insert into public.brand_table (name) values ('Herta Foods');
insert into public.brand_table (name) values ('Hunt''s Snack Pack');
insert into public.brand_table (name) values ('Kozy Shack');
insert into public.brand_table (name) values ('La Choy');
insert into public.brand_table (name) values ('Lean Cuisine');
insert into public.brand_table (name) values ('Mrs. Grass');
insert into public.brand_table (name) values ('Swanson');
insert into public.brand_table (name) values ('Swiss Miss');
insert into public.brand_table (name) values ('Weight Watchers');
insert into public.brand_table (name) values ('Yoplait');
insert into public.brand_table (name) values ('Beerenberg Farm');
insert into public.brand_table (name) values ('Chicken Tonight');
insert into public.brand_table (name) values ('Hayward''s');
insert into public.brand_table (name) values ('Loyd Grossman sauces');
insert into public.brand_table (name) values ('Prego');
insert into public.brand_table (name) values ('Ragú');
insert into public.brand_table (name) values ('Peperami');
insert into public.brand_table (name) values ('Planters nuts');
insert into public.brand_table (name) values ('Pocky');
insert into public.brand_table (name) values ('Slim Jim');
insert into public.brand_table (name) values ('Space Food Sticks');
insert into public.brand_table (name) values ('Cup-a-soup');
insert into public.brand_table (name) values ('Batchelor''s Super Noodles');
insert into public.brand_table (name) values ('Campbells');
insert into public.brand_table (name) values ('Continental');
insert into public.brand_table (name) values ('Cup-a-soup');
insert into public.brand_table (name) values ('Cup Noodles');
insert into public.brand_table (name) values ('Hamburger Helper');
insert into public.brand_table (name) values ('Heinz');
insert into public.brand_table (name) values ('Indomie');
insert into public.brand_table (name) values ('Koka');
insert into public.brand_table (name) values ('Knorr');
insert into public.brand_table (name) values ('Kraft Dinner');
insert into public.brand_table (name) values ('Maggi');
insert into public.brand_table (name) values ('Mie Sedaap');
insert into public.brand_table (name) values ('Mrs. Grass');
insert into public.brand_table (name) values ('Pot Noodle');
insert into public.brand_table (name) values ('Progresso');
insert into public.brand_table (name) values ('Sapporo Ichiban');
insert into public.brand_table (name) values ('Sarimi');
insert into public.brand_table (name) values ('Science Noodles');
insert into public.brand_table (name) values ('Supermi');
insert into public.brand_table (name) values ('Super Noodles');
insert into public.brand_table (name) values ('Wyler''s');
insert into public.brand_table (name) values ('Alpro');
insert into public.brand_table (name) values ('Eden Foods Inc.');
insert into public.brand_table (name) values ('Jif');
insert into public.brand_table (name) values ('Nutella');
insert into public.brand_table (name) values ('Peter Pan');
insert into public.brand_table (name) values ('Skippy');
insert into public.brand_table (name) values ('Squirrel');
insert into public.brand_table (name) values ('Sun-Pat');
insert into public.brand_table (name) values ('Amy''s Kitchen');
insert into public.brand_table (name) values ('Bernard Matthews');
insert into public.brand_table (name) values ('Birds');
insert into public.brand_table (name) values ('Carbolite');
insert into public.brand_table (name) values ('China Doll');
insert into public.brand_table (name) values ('Fleischmann''s Yeast');
insert into public.brand_table (name) values ('General Mills');
insert into public.brand_table (name) values ('Ginsters');
insert into public.brand_table (name) values ('Harina P.A.N.');
insert into public.brand_table (name) values ('Jel Sert');
insert into public.brand_table (name) values ('Minute Rice');
insert into public.brand_table (name) values ('Mrs. Wagner''s Pies');
insert into public.brand_table (name) values ('Quorn');
insert into public.brand_table (name) values ('ReaLemon');
insert into public.brand_table (name) values ('Slim Fast');
insert into public.brand_table (name) values ('Smash');
insert into public.brand_table (name) values ('Square Pie');
insert into public.brand_table (name) values ('Wall''s');