insert into public.brand_table (id, name) values (1, 'Tilapia - Fillets');
insert into public.brand_table (id, name) values (2, 'Juice - Orangina');
insert into public.brand_table (id, name) values (3, 'Split Peas - Green, Dry');
insert into public.brand_table (id, name) values (4, 'Pastry - Banana Muffin - Mini');
insert into public.brand_table (id, name) values (5, 'Daikon Radish');
insert into public.brand_table (id, name) values (6, 'Clam Nectar');
insert into public.brand_table (id, name) values (7, 'Sauce - Soya, Light');
insert into public.brand_table (id, name) values (8, 'Milk 2% 500 Ml');
insert into public.brand_table (id, name) values (9, 'Sauce - Oyster');
insert into public.brand_table (id, name) values (10, 'Pepper - Chillies, Crushed');
insert into public.brand_table (id, name) values (11, 'Jolt Cola');
insert into public.brand_table (id, name) values (12, 'Veal - Heart');
insert into public.brand_table (id, name) values (13, 'Creme De Cacao Mcguines');
insert into public.brand_table (id, name) values (14, 'Pork - Ground');
insert into public.brand_table (id, name) values (15, 'Juice - V8, Tomato');
insert into public.brand_table (id, name) values (16, 'Crab - Meat Combo');
insert into public.brand_table (id, name) values (17, 'Juice - Orange, Concentrate');
insert into public.brand_table (id, name) values (18, 'Red Currants');
insert into public.brand_table (id, name) values (19, 'Salmon - Smoked, Sliced');
insert into public.brand_table (id, name) values (20, 'Chips - Miss Vickies');
insert into public.brand_table (id, name) values (21, 'Oil - Coconut');
insert into public.brand_table (id, name) values (22, 'Container - Clear 32 Oz');
insert into public.brand_table (id, name) values (23, 'Bread - Calabrese Baguette');
insert into public.brand_table (id, name) values (24, 'Oil - Cooking Spray');
insert into public.brand_table (id, name) values (25, 'Tomato - Peeled Italian Canned');
insert into public.brand_table (id, name) values (26, 'Egg - Salad Premix');
insert into public.brand_table (id, name) values (27, 'Veal - Brisket, Provimi, Bone - In');
insert into public.brand_table (id, name) values (28, 'Glaze - Apricot');
insert into public.brand_table (id, name) values (29, 'Clementine');
insert into public.brand_table (id, name) values (30, 'Veal - Slab Bacon');
insert into public.brand_table (id, name) values (31, 'Soup Campbells Mexicali Tortilla');
insert into public.brand_table (id, name) values (32, 'Beans - Soya Bean');
insert into public.brand_table (id, name) values (33, 'Coriander - Ground');
insert into public.brand_table (id, name) values (34, 'Thyme - Dried');
insert into public.brand_table (id, name) values (35, 'Wine - Red, Black Opal Shiraz');
insert into public.brand_table (id, name) values (36, 'Papadam');
insert into public.brand_table (id, name) values (37, 'Pasta - Detalini, White, Fresh');
insert into public.brand_table (id, name) values (38, 'Beef - Shank');
insert into public.brand_table (id, name) values (39, 'Pails With Lids');
insert into public.brand_table (id, name) values (40, 'Island Oasis - Ice Cream Mix');
insert into public.brand_table (id, name) values (41, 'Wine - Guy Sage Touraine');
insert into public.brand_table (id, name) values (42, 'Dawn Professionl Pot And Pan');
insert into public.brand_table (id, name) values (43, 'Vol Au Vents');
insert into public.brand_table (id, name) values (44, 'Mushroom - Trumpet, Dry');
insert into public.brand_table (id, name) values (45, 'Tortillas - Flour, 8');
insert into public.brand_table (id, name) values (46, 'Turkey - Ground. Lean');
insert into public.brand_table (id, name) values (47, 'Beets - Mini Golden');
insert into public.brand_table (id, name) values (48, 'Apron');
insert into public.brand_table (id, name) values (49, 'Bread - Pain Au Liat X12');
insert into public.brand_table (id, name) values (50, 'Cheese - Bocconcini');
insert into public.brand_table (id, name) values (51, 'Maintenance Removal Charge');
insert into public.brand_table (id, name) values (52, 'Green Tea Refresher');
insert into public.brand_table (id, name) values (53, 'Mustard - Pommery');
insert into public.brand_table (id, name) values (54, 'Chicken - White Meat, No Tender');
insert into public.brand_table (id, name) values (55, 'Cheese - Brie,danish');
insert into public.brand_table (id, name) values (56, 'Sobe - Green Tea');
insert into public.brand_table (id, name) values (57, 'Corn Kernels - Frozen');
insert into public.brand_table (id, name) values (58, 'Durian Fruit');
insert into public.brand_table (id, name) values (59, 'Sambuca Cream');
insert into public.brand_table (id, name) values (60, 'Gin - Gilbeys London, Dry');
insert into public.brand_table (id, name) values (61, 'White Fish - Filets');
insert into public.brand_table (id, name) values (62, 'Pineapple - Golden');
insert into public.brand_table (id, name) values (63, 'Bread - Ciabatta Buns');
insert into public.brand_table (id, name) values (64, 'Beef - Top Butt Aaa');
insert into public.brand_table (id, name) values (65, 'Potatoes - Peeled');
insert into public.brand_table (id, name) values (66, 'Wine - Malbec Trapiche Reserve');
insert into public.brand_table (id, name) values (67, 'Chip - Potato Dill Pickle');
insert into public.brand_table (id, name) values (68, 'Coffee - Espresso');
insert into public.brand_table (id, name) values (69, 'Fenngreek Seed');
insert into public.brand_table (id, name) values (70, 'Duck - Whole');
insert into public.brand_table (id, name) values (71, 'Nantucket Apple Juice');
insert into public.brand_table (id, name) values (72, 'Plastic Arrow Stir Stick');
insert into public.brand_table (id, name) values (73, 'Cake - Sheet Strawberry');
insert into public.brand_table (id, name) values (74, 'Tea - Earl Grey');
insert into public.brand_table (id, name) values (75, 'True - Vue Containers');
insert into public.brand_table (id, name) values (76, 'Milk - Homo');
insert into public.brand_table (id, name) values (77, 'Water - Spring Water 500ml');
insert into public.brand_table (id, name) values (78, 'Pepper - Black, Crushed');
insert into public.brand_table (id, name) values (79, 'Bread Bowl Plain');
insert into public.brand_table (id, name) values (80, 'Bols Melon Liqueur');
insert into public.brand_table (id, name) values (81, 'Beef - Bones, Marrow');
insert into public.brand_table (id, name) values (82, 'Lemon Grass');
insert into public.brand_table (id, name) values (83, 'Flounder - Fresh');
insert into public.brand_table (id, name) values (84, 'Graham Cracker Mix');
insert into public.brand_table (id, name) values (85, 'Cloves - Whole');
insert into public.brand_table (id, name) values (86, 'Chicken - Wings, Tip Off');
insert into public.brand_table (id, name) values (87, 'Cheese - Bakers Cream Cheese');
insert into public.brand_table (id, name) values (88, 'Wine - Shiraz Wolf Blass Premium');
insert into public.brand_table (id, name) values (89, 'Chicken - Whole Fryers');
insert into public.brand_table (id, name) values (90, 'Container Clear 8 Oz');
insert into public.brand_table (id, name) values (91, 'Olives - Nicoise');
insert into public.brand_table (id, name) values (92, 'Yogurt - French Vanilla');
insert into public.brand_table (id, name) values (93, 'Beef Flat Iron Steak');
insert into public.brand_table (id, name) values (94, 'Beef - Short Ribs');
insert into public.brand_table (id, name) values (95, 'Ice Cream Bar - Hagen Daz');
insert into public.brand_table (id, name) values (96, 'Cheese - Roquefort Pappillon');
insert into public.brand_table (id, name) values (97, 'Tea - Honey Green Tea');
insert into public.brand_table (id, name) values (98, 'Knife Plastic - White');
insert into public.brand_table (id, name) values (99, 'Lettuce - Arugula');
insert into public.brand_table (id, name) values (100, 'Cactus Pads');
insert into public.brand_table (id, name) values (101, 'Green Scrubbie Pad H.duty');
insert into public.brand_table (id, name) values (102, 'Coffee Caramel Biscotti');
insert into public.brand_table (id, name) values (103, 'Pork - Caul Fat');
insert into public.brand_table (id, name) values (104, 'Gelatine Powder');
insert into public.brand_table (id, name) values (105, 'Apple - Granny Smith');
insert into public.brand_table (id, name) values (106, 'Latex Rubber Gloves Size 9');
insert into public.brand_table (id, name) values (107, 'Butter - Salted, Micro');
insert into public.brand_table (id, name) values (108, 'Ice Cream Bar - Drumstick');
insert into public.brand_table (id, name) values (109, 'Pepper - Gypsy Pepper');
insert into public.brand_table (id, name) values (110, 'Beer - True North Strong Ale');
insert into public.brand_table (id, name) values (111, 'Wiberg Cure');
insert into public.brand_table (id, name) values (112, 'Wine - Lamancha Do Crianza');
insert into public.brand_table (id, name) values (113, 'Table Cloth 54x72 Colour');
insert into public.brand_table (id, name) values (114, 'Jam - Blackberry, 20 Ml Jar');
insert into public.brand_table (id, name) values (115, 'Pork - Ham Hocks - Smoked');
insert into public.brand_table (id, name) values (116, 'Miso Paste White');
insert into public.brand_table (id, name) values (117, 'Sauce - Balsamic Viniagrette');
insert into public.brand_table (id, name) values (118, 'Vinegar - Red Wine');
insert into public.brand_table (id, name) values (119, 'Beef - Ox Tail, Frozen');
insert into public.brand_table (id, name) values (120, 'Glass Clear 7 Oz Xl');
insert into public.brand_table (id, name) values (121, 'Gelatine Powder');
insert into public.brand_table (id, name) values (122, 'Wine - Valpolicella Masi');
insert into public.brand_table (id, name) values (123, 'Mayonnaise - Individual Pkg');
insert into public.brand_table (id, name) values (124, 'Soup Campbells');
insert into public.brand_table (id, name) values (125, 'Bread Base - Gold Formel');
insert into public.brand_table (id, name) values (126, 'Yogurt - Peach, 175 Gr');
insert into public.brand_table (id, name) values (127, 'Dawn Professionl Pot And Pan');
insert into public.brand_table (id, name) values (128, 'Jam - Apricot');
insert into public.brand_table (id, name) values (129, 'Sauce Tomato Pouch');
insert into public.brand_table (id, name) values (130, 'Fish - Soup Base, Bouillon');
insert into public.brand_table (id, name) values (131, 'Crackers - Melba Toast');
insert into public.brand_table (id, name) values (132, 'Tomatoes - Hot House');
insert into public.brand_table (id, name) values (133, 'Ginsing - Fresh');
insert into public.brand_table (id, name) values (134, 'Nut - Walnut, Pieces');
insert into public.brand_table (id, name) values (135, 'Soup - Campbells, Classic Chix');
insert into public.brand_table (id, name) values (136, 'Appetizer - Escargot Puff');
insert into public.brand_table (id, name) values (137, 'Tea - Mint');
insert into public.brand_table (id, name) values (138, 'Mushroom - Shitake, Fresh');
insert into public.brand_table (id, name) values (139, 'Eggplant - Baby');
insert into public.brand_table (id, name) values (140, 'Beer - Rickards Red');
insert into public.brand_table (id, name) values (141, 'Shrimp - 21/25, Peel And Deviened');
insert into public.brand_table (id, name) values (142, 'Maintenance Removal Charge');
insert into public.brand_table (id, name) values (143, 'Pork Loin Bine - In Frenched');
insert into public.brand_table (id, name) values (144, 'Soup - Campbells Chicken');
insert into public.brand_table (id, name) values (145, 'Island Oasis - Sweet And Sour Mix');
insert into public.brand_table (id, name) values (146, 'Bagel - Whole White Sesame');
insert into public.brand_table (id, name) values (147, 'Salt - Table');
insert into public.brand_table (id, name) values (148, 'Beef Ground Medium');
insert into public.brand_table (id, name) values (149, 'Cheese - Cheddar With Claret');
insert into public.brand_table (id, name) values (150, 'Appetizer - Mini Egg Roll, Shrimp');
insert into public.brand_table (id, name) values (151, 'Beer - Sleeman Fine Porter');
insert into public.brand_table (id, name) values (152, 'Hipnotiq Liquor');
insert into public.brand_table (id, name) values (153, 'Veal - Round, Eye Of');
insert into public.brand_table (id, name) values (154, 'Coffee - Colombian, Portioned');
insert into public.brand_table (id, name) values (155, 'Chick Peas - Canned');
insert into public.brand_table (id, name) values (156, 'Water - Spring Water 500ml');
insert into public.brand_table (id, name) values (157, 'Trout - Rainbow, Frozen');
insert into public.brand_table (id, name) values (158, 'Dry Ice');
insert into public.brand_table (id, name) values (159, 'Cookies - Amaretto');
insert into public.brand_table (id, name) values (160, 'Flower - Potmums');
insert into public.brand_table (id, name) values (161, 'Tart - Pecan Butter Squares');
insert into public.brand_table (id, name) values (162, 'Barley - Pearl');
insert into public.brand_table (id, name) values (163, 'Juice - Pineapple, 48 Oz');
insert into public.brand_table (id, name) values (164, 'Bread - French Baquette');
insert into public.brand_table (id, name) values (165, 'Salmon - Canned');
insert into public.brand_table (id, name) values (166, 'Cheese - Bocconcini');
insert into public.brand_table (id, name) values (167, 'Veal - Nuckle');
insert into public.brand_table (id, name) values (168, 'Wine - Red, Metus Rose');
insert into public.brand_table (id, name) values (169, 'Napkin - Beverge, White 2 - Ply');
insert into public.brand_table (id, name) values (170, 'Mortadella');
insert into public.brand_table (id, name) values (171, 'Sugar - Cubes');
insert into public.brand_table (id, name) values (172, 'Bay Leaf');
insert into public.brand_table (id, name) values (173, 'Compound - Pear');
insert into public.brand_table (id, name) values (174, 'Tea - Green');
insert into public.brand_table (id, name) values (175, 'Pur Value');
insert into public.brand_table (id, name) values (176, 'Beer - Moosehead');
insert into public.brand_table (id, name) values (177, 'Plasticspoonblack');
insert into public.brand_table (id, name) values (178, 'Petit Baguette');
insert into public.brand_table (id, name) values (179, 'Wine - Alsace Gewurztraminer');
insert into public.brand_table (id, name) values (180, 'Beef - Texas Style Burger');
insert into public.brand_table (id, name) values (181, 'Turnip - Wax');
insert into public.brand_table (id, name) values (182, 'Gooseberry');
insert into public.brand_table (id, name) values (183, 'Nut - Macadamia');
insert into public.brand_table (id, name) values (184, 'Wine - Bourgogne 2002, La');
insert into public.brand_table (id, name) values (185, 'Juice - Tomato, 10 Oz');
insert into public.brand_table (id, name) values (186, 'Spice - Peppercorn Melange');
insert into public.brand_table (id, name) values (187, 'Island Oasis - Magarita Mix');
insert into public.brand_table (id, name) values (188, 'Bay Leaf Fresh');
insert into public.brand_table (id, name) values (189, 'Dried Cherries');
insert into public.brand_table (id, name) values (190, 'Wine - Niagara,vqa Reisling');
insert into public.brand_table (id, name) values (191, 'Anisette - Mcguiness');
insert into public.brand_table (id, name) values (192, 'Cake - Night And Day Choclate');
insert into public.brand_table (id, name) values (193, 'Salmon Steak - Cohoe 6 Oz');
insert into public.brand_table (id, name) values (194, 'Potato - Sweet');
insert into public.brand_table (id, name) values (195, 'Chicken - Diced, Cooked');
insert into public.brand_table (id, name) values (196, 'Wine - Vineland Estate Semi - Dry');
insert into public.brand_table (id, name) values (197, 'Wine - Valpolicella Masi');
insert into public.brand_table (id, name) values (198, 'Bagel - Everything');
insert into public.brand_table (id, name) values (199, 'Ginger - Ground');
insert into public.brand_table (id, name) values (200, 'Bread - White, Unsliced');
insert into public.brand_table (id, name) values (201, 'Rambutan');
insert into public.brand_table (id, name) values (202, 'Muffin Hinge Container 6');
insert into public.brand_table (id, name) values (203, 'Flounder - Fresh');
insert into public.brand_table (id, name) values (204, 'Magnotta - Bel Paese White');
insert into public.brand_table (id, name) values (205, 'Shrimp - 21/25, Peel And Deviened');
insert into public.brand_table (id, name) values (206, 'Pomegranates');
insert into public.brand_table (id, name) values (207, 'Spice - Onion Powder Granulated');
insert into public.brand_table (id, name) values (208, 'Lentils - Green, Dry');
insert into public.brand_table (id, name) values (209, 'Beef Cheek Fresh');
insert into public.brand_table (id, name) values (210, 'Broccoli - Fresh');
insert into public.brand_table (id, name) values (211, 'Wine - Charddonnay Errazuriz');
insert into public.brand_table (id, name) values (212, 'Cheese - Provolone');
insert into public.brand_table (id, name) values (213, 'Cheese - Shred Cheddar / Mozza');
insert into public.brand_table (id, name) values (214, 'Wine - Manischewitz Concord');
insert into public.brand_table (id, name) values (215, 'Wine - Rubyport');
insert into public.brand_table (id, name) values (216, 'Dates');
insert into public.brand_table (id, name) values (217, 'Flour - Strong');
insert into public.brand_table (id, name) values (218, 'Lamb - Ground');
insert into public.brand_table (id, name) values (219, 'Muffin Mix - Banana Nut');
insert into public.brand_table (id, name) values (220, 'Wine - White, Schroder And Schyl');
insert into public.brand_table (id, name) values (221, 'Oyster - In Shell');
insert into public.brand_table (id, name) values (222, 'Chinese Foods - Plain Fried Rice');
insert into public.brand_table (id, name) values (223, 'Lychee');
insert into public.brand_table (id, name) values (224, 'Halibut - Fletches');
insert into public.brand_table (id, name) values (225, 'Pasta - Fusili Tri - Coloured');
insert into public.brand_table (id, name) values (226, 'Eggplant - Baby');
insert into public.brand_table (id, name) values (227, 'Fireball Whisky');
insert into public.brand_table (id, name) values (228, 'Cheese - Goat With Herbs');
insert into public.brand_table (id, name) values (229, 'Wine - Piper Heidsieck Brut');
insert into public.brand_table (id, name) values (230, 'Squash - Acorn');
insert into public.brand_table (id, name) values (231, 'Artichoke - Bottom, Canned');
insert into public.brand_table (id, name) values (232, 'Beets - Candy Cane, Organic');
insert into public.brand_table (id, name) values (233, 'Apple - Delicious, Red');
insert into public.brand_table (id, name) values (234, 'Tea - Darjeeling, Azzura');
insert into public.brand_table (id, name) values (235, 'Tart - Raisin And Pecan');
insert into public.brand_table (id, name) values (236, 'Milk - Condensed');
insert into public.brand_table (id, name) values (237, 'Fish - Atlantic Salmon, Cold');
insert into public.brand_table (id, name) values (238, 'Cake - Mini Potato Pancake');
insert into public.brand_table (id, name) values (239, 'Monkfish Fresh - Skin Off');
insert into public.brand_table (id, name) values (240, 'Octopus - Baby, Cleaned');
insert into public.brand_table (id, name) values (241, 'Pasta - Fettuccine, Dry');
insert into public.brand_table (id, name) values (242, 'Juice - Tomato, 48 Oz');
insert into public.brand_table (id, name) values (243, 'White Fish - Filets');
insert into public.brand_table (id, name) values (244, 'Pepper - Black, Ground');
insert into public.brand_table (id, name) values (245, 'Pear - Packum');
insert into public.brand_table (id, name) values (246, 'Wine - Shiraz South Eastern');
insert into public.brand_table (id, name) values (247, 'Island Oasis - Mango Daiquiri');
insert into public.brand_table (id, name) values (248, 'Chocolate - Semi Sweet, Calets');
insert into public.brand_table (id, name) values (249, 'Artichoke - Fresh');
insert into public.brand_table (id, name) values (250, 'Bread - Sour Sticks With Onion');
insert into public.brand_table (id, name) values (251, 'Cheese - Cambozola');
insert into public.brand_table (id, name) values (252, 'Bread - Raisin');
insert into public.brand_table (id, name) values (253, 'Puff Pastry - Sheets');
insert into public.brand_table (id, name) values (254, 'Grenadine');
insert into public.brand_table (id, name) values (255, 'Pork Loin Cutlets');
insert into public.brand_table (id, name) values (256, 'Soup - Chicken And Wild Rice');
insert into public.brand_table (id, name) values (257, 'Soup - Chicken And Wild Rice');
insert into public.brand_table (id, name) values (258, 'Beef - Rib Roast, Cap On');
insert into public.brand_table (id, name) values (259, 'Squid - U - 10 Thailand');
insert into public.brand_table (id, name) values (260, 'Lobster - Tail 6 Oz');
insert into public.brand_table (id, name) values (261, 'Hickory Smoke, Liquid');
insert into public.brand_table (id, name) values (262, 'The Pop Shoppe - Lime Rickey');
insert into public.brand_table (id, name) values (263, 'Lid Tray - 16in Dome');
insert into public.brand_table (id, name) values (264, 'Lady Fingers');
insert into public.brand_table (id, name) values (265, 'Eggs - Extra Large');
insert into public.brand_table (id, name) values (266, 'Straw - Regular');
insert into public.brand_table (id, name) values (267, 'Beans - Navy, Dry');
insert into public.brand_table (id, name) values (268, 'Coke - Classic, 355 Ml');
insert into public.brand_table (id, name) values (269, 'Peppercorns - Green');
insert into public.brand_table (id, name) values (270, 'Pork - Bacon Cooked Slcd');
insert into public.brand_table (id, name) values (271, 'Trout - Smoked');
insert into public.brand_table (id, name) values (272, 'Pasta - Fettuccine, Egg, Fresh');
insert into public.brand_table (id, name) values (273, 'Catfish - Fillets');
insert into public.brand_table (id, name) values (274, 'Wine - White, Schroder And Schyl');
insert into public.brand_table (id, name) values (275, 'Creme De Cacao Mcguines');
insert into public.brand_table (id, name) values (276, 'Taro Root');
insert into public.brand_table (id, name) values (277, 'Yogurt - Blueberry, 175 Gr');
insert into public.brand_table (id, name) values (278, 'Hot Chocolate - Individual');
insert into public.brand_table (id, name) values (279, 'Syrup - Monin - Blue Curacao');
insert into public.brand_table (id, name) values (280, 'Crab - Back Fin Meat, Canned');
insert into public.brand_table (id, name) values (281, 'Muffins - Assorted');
insert into public.brand_table (id, name) values (282, 'Wine - Sawmill Creek Autumn');
insert into public.brand_table (id, name) values (283, 'Honey - Comb');
insert into public.brand_table (id, name) values (284, 'Tomatoes - Yellow Hot House');
insert into public.brand_table (id, name) values (285, 'Mushroom Morel Fresh');
insert into public.brand_table (id, name) values (286, 'Oil - Pumpkinseed');
insert into public.brand_table (id, name) values (287, 'Mushroom - Enoki, Dry');
insert into public.brand_table (id, name) values (288, 'Jam - Apricot');
insert into public.brand_table (id, name) values (289, 'Duck - Breast');
insert into public.brand_table (id, name) values (290, 'Lamb - Leg, Boneless');
insert into public.brand_table (id, name) values (291, 'Cumin - Ground');
insert into public.brand_table (id, name) values (292, 'Beans - Turtle, Black, Dry');
insert into public.brand_table (id, name) values (293, 'Assorted Desserts');
insert into public.brand_table (id, name) values (294, 'Plasticspoonblack');
insert into public.brand_table (id, name) values (295, 'Duck - Legs');
insert into public.brand_table (id, name) values (296, 'Wine La Vielle Ferme Cote Du');
insert into public.brand_table (id, name) values (297, 'Cup - 6oz, Foam');
insert into public.brand_table (id, name) values (298, 'Sobe - Lizard Fuel');
insert into public.brand_table (id, name) values (299, 'Vinegar - Raspberry');
insert into public.brand_table (id, name) values (300, 'Dill Weed - Dry');
insert into public.brand_table (id, name) values (301, 'Myers Planters Punch');
insert into public.brand_table (id, name) values (302, 'Caviar - Salmon');
insert into public.brand_table (id, name) values (303, 'Cheese - Montery Jack');
insert into public.brand_table (id, name) values (304, 'Cheese - Swiss Sliced');
insert into public.brand_table (id, name) values (305, 'Cheese - Swiss');
insert into public.brand_table (id, name) values (306, 'Bread - Hot Dog Buns');
insert into public.brand_table (id, name) values (307, 'Stock - Chicken, White');
insert into public.brand_table (id, name) values (308, 'Squeeze Bottle');
insert into public.brand_table (id, name) values (309, 'Tomatoes - Hot House');
insert into public.brand_table (id, name) values (310, 'Orange Roughy 4/6 Oz');
insert into public.brand_table (id, name) values (311, 'Juice - Apple, 500 Ml');
insert into public.brand_table (id, name) values (312, 'Bar Special K');
insert into public.brand_table (id, name) values (313, 'Kirsch - Schloss');
insert into public.brand_table (id, name) values (314, 'Tart - Pecan Butter Squares');
insert into public.brand_table (id, name) values (315, 'Foil - Round Foil');
insert into public.brand_table (id, name) values (316, 'Bar Mix - Lemon');
insert into public.brand_table (id, name) values (317, 'Sultanas');
insert into public.brand_table (id, name) values (318, 'Pepper - White, Ground');
insert into public.brand_table (id, name) values (319, 'Steampan Lid');
insert into public.brand_table (id, name) values (320, 'Myers Planters Punch');
insert into public.brand_table (id, name) values (321, 'Pasta - Lasagna, Dry');
insert into public.brand_table (id, name) values (322, 'Crab - Meat');
insert into public.brand_table (id, name) values (323, 'Chilli Paste, Ginger Garlic');
insert into public.brand_table (id, name) values (324, 'Pears - Fiorelle');
insert into public.brand_table (id, name) values (325, 'Chicken Breast Wing On');
insert into public.brand_table (id, name) values (326, 'Pail - 4l White, With Handle');
insert into public.brand_table (id, name) values (327, 'Cookie Dough - Chunky');
insert into public.brand_table (id, name) values (328, 'Bread Crumbs - Panko');
insert into public.brand_table (id, name) values (329, 'Eggplant Italian');
insert into public.brand_table (id, name) values (330, 'Chutney Sauce - Mango');
insert into public.brand_table (id, name) values (331, 'Phyllo Dough');
insert into public.brand_table (id, name) values (332, 'Wine - Chablis 2003 Champs');
insert into public.brand_table (id, name) values (333, 'Smirnoff Green Apple Twist');
insert into public.brand_table (id, name) values (334, 'V8 Splash Strawberry Banana');
insert into public.brand_table (id, name) values (335, 'Ham Black Forest');
insert into public.brand_table (id, name) values (336, 'Rambutan');
insert into public.brand_table (id, name) values (337, 'Amarula Cream');
insert into public.brand_table (id, name) values (338, 'Wine - Semi Dry Riesling Vineland');
insert into public.brand_table (id, name) values (339, 'Lettuce - Frisee');
insert into public.brand_table (id, name) values (340, 'Flour - Rye');
insert into public.brand_table (id, name) values (341, 'Beer - Camerons Cream Ale');
insert into public.brand_table (id, name) values (342, 'Cheese - Stilton');
insert into public.brand_table (id, name) values (343, 'Cake - Lemon Chiffon');
insert into public.brand_table (id, name) values (344, 'Chocolate - Unsweetened');
insert into public.brand_table (id, name) values (345, 'Wine - Merlot Vina Carmen');
insert into public.brand_table (id, name) values (346, 'Soho Lychee Liqueur');
insert into public.brand_table (id, name) values (347, 'Yeast - Fresh, Fleischman');
insert into public.brand_table (id, name) values (348, 'Chicken Giblets');
insert into public.brand_table (id, name) values (349, 'Yogurt - Banana, 175 Gr');
insert into public.brand_table (id, name) values (350, 'Cup - Paper 10oz 92959');
insert into public.brand_table (id, name) values (351, 'Corn - Mini');
insert into public.brand_table (id, name) values (352, 'Ice Cream - Chocolate');
insert into public.brand_table (id, name) values (353, 'Fork - Plastic');
insert into public.brand_table (id, name) values (354, 'Mushrooms - Black, Dried');
insert into public.brand_table (id, name) values (355, 'Sesame Seed');
insert into public.brand_table (id, name) values (356, 'Lid Tray - 12in Dome');
insert into public.brand_table (id, name) values (357, 'Pail For Lid 1537');
insert into public.brand_table (id, name) values (358, 'Water - San Pellegrino');
insert into public.brand_table (id, name) values (359, 'Coffee Cup 16oz Foam');
insert into public.brand_table (id, name) values (360, 'Beef Wellington');
insert into public.brand_table (id, name) values (361, 'Lamb - Shoulder, Boneless');
insert into public.brand_table (id, name) values (362, 'Water - San Pellegrino');
insert into public.brand_table (id, name) values (363, 'Pineapple - Regular');
insert into public.brand_table (id, name) values (364, 'Wine - Remy Pannier Rose');
insert into public.brand_table (id, name) values (365, 'Filo Dough');
insert into public.brand_table (id, name) values (366, 'Soupcontfoam16oz 116con');
insert into public.brand_table (id, name) values (367, 'Creamers - 10%');
insert into public.brand_table (id, name) values (368, 'Pepperoni Slices');
insert into public.brand_table (id, name) values (369, 'Chocolate - Dark Callets');
insert into public.brand_table (id, name) values (370, 'Kiwi');
insert into public.brand_table (id, name) values (371, 'Bread - Italian Roll With Herbs');
insert into public.brand_table (id, name) values (372, 'Pepper - Black, Whole');
insert into public.brand_table (id, name) values (373, 'Cinnamon Rolls');
insert into public.brand_table (id, name) values (374, 'Lychee - Canned');
insert into public.brand_table (id, name) values (375, 'Cheese - St. Paulin');
insert into public.brand_table (id, name) values (376, 'Peas - Frozen');
insert into public.brand_table (id, name) values (377, 'Ginger - Pickled');
insert into public.brand_table (id, name) values (378, 'Table Cloth 90x90 Colour');
insert into public.brand_table (id, name) values (379, 'Pickles - Gherkins');
insert into public.brand_table (id, name) values (380, 'Nut - Almond, Blanched, Sliced');
insert into public.brand_table (id, name) values (381, 'Garbage Bags - Black');
insert into public.brand_table (id, name) values (382, 'Towel Multifold');
insert into public.brand_table (id, name) values (383, 'Mustard Prepared');
insert into public.brand_table (id, name) values (384, 'Sorrel - Fresh');
insert into public.brand_table (id, name) values (385, 'Ice Cream Bar - Drumstick');
insert into public.brand_table (id, name) values (386, 'Island Oasis - Mango Daiquiri');
insert into public.brand_table (id, name) values (387, 'Bread - Pullman, Sliced');
insert into public.brand_table (id, name) values (388, 'Couscous');
insert into public.brand_table (id, name) values (389, 'Oil - Shortening,liqud, Fry');
insert into public.brand_table (id, name) values (390, 'Oil - Pumpkinseed');
insert into public.brand_table (id, name) values (391, 'Sprouts - China Rose');
insert into public.brand_table (id, name) values (392, 'Olives - Black, Pitted');
insert into public.brand_table (id, name) values (393, 'Cod - Black Whole Fillet');
insert into public.brand_table (id, name) values (394, 'Sweet Pea Sprouts');
insert into public.brand_table (id, name) values (395, 'Muffin Chocolate Individual Wrap');
insert into public.brand_table (id, name) values (396, 'Tofu - Soft');
insert into public.brand_table (id, name) values (397, 'Tuna - Salad Premix');
insert into public.brand_table (id, name) values (398, 'Pepper - Chilli Seeds Mild');
insert into public.brand_table (id, name) values (399, 'Lemon Pepper');
insert into public.brand_table (id, name) values (400, 'Pepper - Red, Finger Hot');
insert into public.brand_table (id, name) values (401, 'Coke - Diet, 355 Ml');
insert into public.brand_table (id, name) values (402, 'Wine - Chateau Timberlay');
insert into public.brand_table (id, name) values (403, 'Shrimp - Prawn');
insert into public.brand_table (id, name) values (404, 'Wheat - Soft Kernal Of Wheat');
insert into public.brand_table (id, name) values (405, 'Tofu - Firm');
insert into public.brand_table (id, name) values (406, 'Cheese - Feta');
insert into public.brand_table (id, name) values (407, 'Roe - Flying Fish');
insert into public.brand_table (id, name) values (408, 'Cinnamon Buns Sticky');
insert into public.brand_table (id, name) values (409, 'Apricots - Halves');
insert into public.brand_table (id, name) values (410, 'Juice - Cranberry 284ml');
insert into public.brand_table (id, name) values (411, 'Sprouts - Brussel');
insert into public.brand_table (id, name) values (412, 'Whmis Spray Bottle Graduated');
insert into public.brand_table (id, name) values (413, 'Vinegar - Champagne');
insert into public.brand_table (id, name) values (414, 'Paper Towel Touchless');
insert into public.brand_table (id, name) values (415, 'Bacardi Mojito');
insert into public.brand_table (id, name) values (416, 'Shrimp - Black Tiger 13/15');
insert into public.brand_table (id, name) values (417, 'Pork - Belly Fresh');
insert into public.brand_table (id, name) values (418, 'Appetizer - Lobster Phyllo Roll');
insert into public.brand_table (id, name) values (419, 'Soho Lychee Liqueur');
insert into public.brand_table (id, name) values (420, 'Prunes - Pitted');
insert into public.brand_table (id, name) values (421, 'Vinegar - Balsamic');
insert into public.brand_table (id, name) values (422, 'Nori Sea Weed - Gold Label');
insert into public.brand_table (id, name) values (423, 'Ezy Change Mophandle');
insert into public.brand_table (id, name) values (424, 'Tofu - Soft');
insert into public.brand_table (id, name) values (425, 'Bread - Bagels, Mini');
insert into public.brand_table (id, name) values (426, 'Bread - Rosemary Focaccia');
insert into public.brand_table (id, name) values (427, 'Swiss Chard');
insert into public.brand_table (id, name) values (428, 'Water - Green Tea Refresher');
insert into public.brand_table (id, name) values (429, 'Beans - Green');
insert into public.brand_table (id, name) values (430, 'Kellogs Cereal In A Cup');
insert into public.brand_table (id, name) values (431, 'Turnip - White');
insert into public.brand_table (id, name) values (432, 'Wine - Sogrape Mateus Rose');
insert into public.brand_table (id, name) values (433, 'Alize Gold Passion');
insert into public.brand_table (id, name) values (434, 'Salt - Kosher');
insert into public.brand_table (id, name) values (435, 'Cabbage - Red');
insert into public.brand_table (id, name) values (436, 'Asparagus - White, Canned');
insert into public.brand_table (id, name) values (437, 'Carrots - Purple, Organic');
insert into public.brand_table (id, name) values (438, 'Crab - Meat Combo');
insert into public.brand_table (id, name) values (439, 'Veal - Liver');
insert into public.brand_table (id, name) values (440, 'Coffee - 10oz Cup 92961');
insert into public.brand_table (id, name) values (441, 'Sugar - Sweet N Low, Individual');
insert into public.brand_table (id, name) values (442, 'Mini - Vol Au Vents');
insert into public.brand_table (id, name) values (443, 'Soup - Campbells, Chix Gumbo');
insert into public.brand_table (id, name) values (444, 'Chocolate Liqueur - Godet White');
insert into public.brand_table (id, name) values (445, 'Veal - Brisket, Provimi, Bone - In');
insert into public.brand_table (id, name) values (446, 'Ocean Spray - Kiwi Strawberry');
insert into public.brand_table (id, name) values (447, 'Pork - Loin, Center Cut');
insert into public.brand_table (id, name) values (448, 'Nantucket Cranberry Juice');
insert into public.brand_table (id, name) values (449, 'Muffin Mix - Corn Harvest');
insert into public.brand_table (id, name) values (450, 'Kumquat');
insert into public.brand_table (id, name) values (451, 'Butter Ripple - Phillips');
insert into public.brand_table (id, name) values (452, 'Dikon');
insert into public.brand_table (id, name) values (453, 'Sprouts Dikon');
insert into public.brand_table (id, name) values (454, 'Pail For Lid 1537');
insert into public.brand_table (id, name) values (455, 'Jicama');
insert into public.brand_table (id, name) values (456, 'Lychee - Canned');
insert into public.brand_table (id, name) values (457, 'Milk - Buttermilk');
insert into public.brand_table (id, name) values (458, 'Sachet');
insert into public.brand_table (id, name) values (459, 'Cut Wakame - Hanawakaba');
insert into public.brand_table (id, name) values (460, 'Fudge - Chocolate Fudge');
insert into public.brand_table (id, name) values (461, 'Bread - Pita, Mini');
insert into public.brand_table (id, name) values (462, 'Crackers Cheez It');
insert into public.brand_table (id, name) values (463, 'Table Cloth 54x54 Colour');
insert into public.brand_table (id, name) values (464, 'Tea - Camomele');
insert into public.brand_table (id, name) values (465, 'Beer - Paulaner Hefeweisse');
insert into public.brand_table (id, name) values (466, 'Vegetable - Base');
insert into public.brand_table (id, name) values (467, 'Scotch - Queen Anne');
insert into public.brand_table (id, name) values (468, 'Sage - Fresh');
insert into public.brand_table (id, name) values (469, 'Beans - Kidney, Canned');
insert into public.brand_table (id, name) values (470, 'Carrots - Purple, Organic');
insert into public.brand_table (id, name) values (471, 'Nut - Pumpkin Seeds');
insert into public.brand_table (id, name) values (472, 'Wine - Cousino Macul Antiguas');
insert into public.brand_table (id, name) values (473, 'Longos - Assorted Sandwich');
insert into public.brand_table (id, name) values (474, 'Gatorade - Orange');
insert into public.brand_table (id, name) values (475, 'Beans - Soya Bean');
insert into public.brand_table (id, name) values (476, 'Beef - Roasted, Cooked');
insert into public.brand_table (id, name) values (477, 'Glucose');
insert into public.brand_table (id, name) values (478, 'Chocolate - Mi - Amere Semi');
insert into public.brand_table (id, name) values (479, 'Fireball Whisky');
insert into public.brand_table (id, name) values (480, 'Clementine');
insert into public.brand_table (id, name) values (481, 'Tart Shells - Savory, 2');
insert into public.brand_table (id, name) values (482, 'Compound - Mocha');
insert into public.brand_table (id, name) values (483, 'Yogurt - Strawberry, 175 Gr');
insert into public.brand_table (id, name) values (484, 'Beef - Tenderloin');
insert into public.brand_table (id, name) values (485, 'Cinnamon - Ground');
insert into public.brand_table (id, name) values (486, 'Ice Cream - Life Savers');
insert into public.brand_table (id, name) values (487, 'Brownies - Two Bite, Chocolate');
insert into public.brand_table (id, name) values (488, 'Cream - 18%');
insert into public.brand_table (id, name) values (489, 'Beef Tenderloin Aaa');
insert into public.brand_table (id, name) values (490, 'Bagel - Everything');
insert into public.brand_table (id, name) values (491, 'Juice - Orange, 341 Ml');
insert into public.brand_table (id, name) values (492, 'Bacardi Breezer - Tropical');
insert into public.brand_table (id, name) values (493, 'Pork - Shoulder');
insert into public.brand_table (id, name) values (494, 'Chinese Lemon Pork');
insert into public.brand_table (id, name) values (495, 'Juice - Happy Planet');
insert into public.brand_table (id, name) values (496, 'Wine - Masi Valpolocell');
insert into public.brand_table (id, name) values (497, 'Kirsch - Schloss');
insert into public.brand_table (id, name) values (498, 'Mushroom - Portebello');
insert into public.brand_table (id, name) values (499, 'Island Oasis - Ice Cream Mix');
insert into public.brand_table (id, name) values (500, 'Scallops - 20/30');
insert into public.brand_table (id, name) values (501, 'Cookie - Dough Variety');
insert into public.brand_table (id, name) values (502, 'Nantucket - 518ml');
insert into public.brand_table (id, name) values (503, 'Compound - Rum');
insert into public.brand_table (id, name) values (504, 'Tandoori Curry Paste');
insert into public.brand_table (id, name) values (505, 'Pasta - Fusili Tri - Coloured');
insert into public.brand_table (id, name) values (506, 'Eel - Smoked');
insert into public.brand_table (id, name) values (507, 'Carrots - Jumbo');
insert into public.brand_table (id, name) values (508, 'Dill Weed - Dry');
insert into public.brand_table (id, name) values (509, 'Sobe - Liz Blizz');
insert into public.brand_table (id, name) values (510, 'Veal - Shank, Pieces');
insert into public.brand_table (id, name) values (511, 'Anisette - Mcguiness');
insert into public.brand_table (id, name) values (512, 'Chocolate - Milk, Callets');
insert into public.brand_table (id, name) values (513, 'Lamb - Leg, Bone In');
insert into public.brand_table (id, name) values (514, 'Salami - Genova');
insert into public.brand_table (id, name) values (515, 'Napkin Colour');
insert into public.brand_table (id, name) values (516, 'Magnotta - Bel Paese White');
insert into public.brand_table (id, name) values (517, 'Potatoes - Idaho 80 Count');
insert into public.brand_table (id, name) values (518, 'Veal - Sweetbread');
insert into public.brand_table (id, name) values (519, 'Compound - Mocha');
insert into public.brand_table (id, name) values (520, 'Juice - Apple 284ml');
insert into public.brand_table (id, name) values (521, 'Wonton Wrappers');
insert into public.brand_table (id, name) values (522, 'Wine - Red, Harrow Estates, Cab');
insert into public.brand_table (id, name) values (523, 'Apples - Sliced / Wedge');
insert into public.brand_table (id, name) values (524, 'Puree - Blackcurrant');
insert into public.brand_table (id, name) values (525, 'Capon - Whole');
insert into public.brand_table (id, name) values (526, 'Thermometer Digital');
insert into public.brand_table (id, name) values (527, 'Fenngreek Seed');
insert into public.brand_table (id, name) values (528, 'Lemonade - Island Tea, 591 Ml');
insert into public.brand_table (id, name) values (529, 'Vinegar - Balsamic, White');
insert into public.brand_table (id, name) values (530, 'Nut - Pistachio, Shelled');
insert into public.brand_table (id, name) values (531, 'Ice Cream - Turtles Stick Bar');
insert into public.brand_table (id, name) values (532, 'Wine - Prosecco Valdobienne');
insert into public.brand_table (id, name) values (533, 'Butter Sweet');
insert into public.brand_table (id, name) values (534, 'Sun - Dried Tomatoes');
insert into public.brand_table (id, name) values (535, 'Eggplant - Regular');
insert into public.brand_table (id, name) values (536, 'Corn - Cream, Canned');
insert into public.brand_table (id, name) values (537, 'Sauce - Soy Low Sodium - 3.87l');
insert into public.brand_table (id, name) values (538, 'Macaroons - Homestyle Two Bit');
insert into public.brand_table (id, name) values (539, 'Bread - Frozen Basket Variety');
insert into public.brand_table (id, name) values (540, 'Pickle - Dill');
insert into public.brand_table (id, name) values (541, 'Sauce - Balsamic Viniagrette');
insert into public.brand_table (id, name) values (542, 'Cheese - Parmesan Grated');
insert into public.brand_table (id, name) values (543, 'Crab - Back Fin Meat, Canned');
insert into public.brand_table (id, name) values (544, 'Pepper - Pablano');
insert into public.brand_table (id, name) values (545, 'Venison - Ground');
insert into public.brand_table (id, name) values (546, 'Tuna - Sushi Grade');
insert into public.brand_table (id, name) values (547, 'Appetizer - Veg Assortment');
insert into public.brand_table (id, name) values (548, 'Cattail Hearts');
insert into public.brand_table (id, name) values (549, 'Sauce - Chili');
insert into public.brand_table (id, name) values (550, 'Beef - Sushi Flat Iron Steak');
insert into public.brand_table (id, name) values (551, 'Wine - Jackson Triggs Okonagan');
insert into public.brand_table (id, name) values (552, 'Yogurt - French Vanilla');
insert into public.brand_table (id, name) values (553, 'Yukon Jack');
insert into public.brand_table (id, name) values (554, 'Salmon - Canned');
insert into public.brand_table (id, name) values (555, 'Sponge Cake Mix - Chocolate');
insert into public.brand_table (id, name) values (556, 'Food Colouring - Green');
insert into public.brand_table (id, name) values (557, 'Ostrich - Prime Cut');
insert into public.brand_table (id, name) values (558, 'Strawberries');
insert into public.brand_table (id, name) values (559, 'Sprite, Diet - 355ml');
insert into public.brand_table (id, name) values (560, 'Turkey Tenderloin Frozen');
insert into public.brand_table (id, name) values (561, 'Tea - Jasmin Green');
insert into public.brand_table (id, name) values (562, 'Pork - Loin, Boneless');
insert into public.brand_table (id, name) values (563, 'Cinnamon Buns Sticky');
insert into public.brand_table (id, name) values (564, 'Ham - Procutinni');
insert into public.brand_table (id, name) values (565, 'Tuna - Sushi Grade');
insert into public.brand_table (id, name) values (566, 'Marsala - Sperone, Fine, D.o.c.');
insert into public.brand_table (id, name) values (567, 'Wine - Magnotta - Cab Sauv');
insert into public.brand_table (id, name) values (568, 'Bread - Rosemary Focaccia');
insert into public.brand_table (id, name) values (569, 'Shrimp - Baby, Cold Water');
insert into public.brand_table (id, name) values (570, 'Chicken - Ground');
insert into public.brand_table (id, name) values (571, 'Carrots - Mini, Stem On');
insert into public.brand_table (id, name) values (572, 'Pomegranates');
insert into public.brand_table (id, name) values (573, 'Nougat - Paste / Cream');
insert into public.brand_table (id, name) values (574, 'Magnotta - Bel Paese White');
insert into public.brand_table (id, name) values (575, 'Beets');
insert into public.brand_table (id, name) values (576, 'Lettuce - Baby Salad Greens');
insert into public.brand_table (id, name) values (577, 'Cookie Dough - Double');
insert into public.brand_table (id, name) values (578, 'Cheese - Goat');
insert into public.brand_table (id, name) values (579, 'Lemonade - Mandarin, 591 Ml');
insert into public.brand_table (id, name) values (580, 'Juice - Apple Cider');
insert into public.brand_table (id, name) values (581, 'Table Cloth 62x114 White');
insert into public.brand_table (id, name) values (582, 'Tofu - Firm');
insert into public.brand_table (id, name) values (583, 'Coffee - Almond Amaretto');
insert into public.brand_table (id, name) values (584, 'Flavouring - Rum');
insert into public.brand_table (id, name) values (585, 'Chicken - Tenderloin');
insert into public.brand_table (id, name) values (586, 'Pernod');
insert into public.brand_table (id, name) values (587, 'Bacardi Breezer - Tropical');
insert into public.brand_table (id, name) values (588, 'Pepper - Jalapeno');
insert into public.brand_table (id, name) values (589, 'Bread - 10 Grain');
insert into public.brand_table (id, name) values (590, 'Vaccum Bag 10x13');
insert into public.brand_table (id, name) values (591, 'Cheese - Blue');
insert into public.brand_table (id, name) values (592, 'Juice - Propel Sport');
insert into public.brand_table (id, name) values (593, 'Foil Wrap');
insert into public.brand_table (id, name) values (594, 'Sprouts - Brussel');
insert into public.brand_table (id, name) values (595, 'Hand Towel');
insert into public.brand_table (id, name) values (596, 'Flour - Pastry');
insert into public.brand_table (id, name) values (597, 'Crab - Soft Shell');
insert into public.brand_table (id, name) values (598, 'Kirsch - Schloss');
insert into public.brand_table (id, name) values (599, 'Tomatoes - Vine Ripe, Yellow');
insert into public.brand_table (id, name) values (600, 'Eggs - Extra Large');
insert into public.brand_table (id, name) values (601, 'Flour - Corn, Fine');
insert into public.brand_table (id, name) values (602, 'Coriander - Ground');
insert into public.brand_table (id, name) values (603, 'Pastry - Apple Muffins - Mini');
insert into public.brand_table (id, name) values (604, 'Chestnuts - Whole,canned');
insert into public.brand_table (id, name) values (605, 'Wine - Penfolds Koonuga Hill');
insert into public.brand_table (id, name) values (606, 'Monkfish - Fresh');
insert into public.brand_table (id, name) values (607, 'Peppercorns - Pink');
insert into public.brand_table (id, name) values (608, 'Garbage Bag - Clear');
insert into public.brand_table (id, name) values (609, 'Jolt Cola - Electric Blue');
insert into public.brand_table (id, name) values (610, 'Cheese - Goat With Herbs');
insert into public.brand_table (id, name) values (611, 'Pear - Halves');
insert into public.brand_table (id, name) values (612, 'Beef - Ox Tail, Frozen');
insert into public.brand_table (id, name) values (613, 'Veal - Ground');
insert into public.brand_table (id, name) values (614, 'Wine - Red, Cabernet Merlot');
insert into public.brand_table (id, name) values (615, 'Nut - Almond, Blanched, Whole');
insert into public.brand_table (id, name) values (616, 'Longos - Cheese Tortellini');
insert into public.brand_table (id, name) values (617, 'Cafe Royale');
insert into public.brand_table (id, name) values (618, 'Initation Crab Meat');
insert into public.brand_table (id, name) values (619, 'Cornstarch');
insert into public.brand_table (id, name) values (620, 'Bacardi Breezer - Tropical');
insert into public.brand_table (id, name) values (621, 'Shrimp - 150 - 250');
insert into public.brand_table (id, name) values (622, 'Wine - Casablanca Valley');
insert into public.brand_table (id, name) values (623, 'Spinach - Frozen');
insert into public.brand_table (id, name) values (624, 'Basil - Seedlings Cookstown');
insert into public.brand_table (id, name) values (625, 'Nut - Almond, Blanched, Sliced');
insert into public.brand_table (id, name) values (626, 'Brandy - Orange, Mc Guiness');
insert into public.brand_table (id, name) values (627, 'Rhubarb');
insert into public.brand_table (id, name) values (628, 'Wine - Remy Pannier Rose');
insert into public.brand_table (id, name) values (629, 'Ice Cream - Vanilla');
insert into public.brand_table (id, name) values (630, 'Bacon Strip Precooked');
insert into public.brand_table (id, name) values (631, 'Flower - Carnations');
insert into public.brand_table (id, name) values (632, 'Flavouring - Raspberry');
insert into public.brand_table (id, name) values (633, 'Beer - Molson Excel');
insert into public.brand_table (id, name) values (634, 'Quail Eggs - Canned');
insert into public.brand_table (id, name) values (635, 'Scallops - 20/30');
insert into public.brand_table (id, name) values (636, 'Grand Marnier');
insert into public.brand_table (id, name) values (637, 'Flax Seed');
insert into public.brand_table (id, name) values (638, 'Veal - Kidney');
insert into public.brand_table (id, name) values (639, 'Pork Casing');
insert into public.brand_table (id, name) values (640, 'Appetizer - Mushroom Tart');
insert into public.brand_table (id, name) values (641, 'Oven Mitts - 15 Inch');
insert into public.brand_table (id, name) values (642, 'Syrup - Golden, Lyles');
insert into public.brand_table (id, name) values (643, 'Wine - Chardonnay Mondavi');
insert into public.brand_table (id, name) values (644, 'Chicken - Leg, Fresh');
insert into public.brand_table (id, name) values (645, 'True - Vue Containers');
insert into public.brand_table (id, name) values (646, 'Liquid Aminios Acid - Braggs');
insert into public.brand_table (id, name) values (647, 'Coffee - Beans, Whole');
insert into public.brand_table (id, name) values (648, 'Compound - Mocha');
insert into public.brand_table (id, name) values (649, 'Soup - Campbells Pasta Fagioli');
insert into public.brand_table (id, name) values (650, 'Potatoes - Mini White 3 Oz');
insert into public.brand_table (id, name) values (651, 'Chicken Breast Halal');
insert into public.brand_table (id, name) values (652, 'Orange - Canned, Mandarin');
insert into public.brand_table (id, name) values (653, 'Salmon - Whole, 4 - 6 Pounds');
insert into public.brand_table (id, name) values (654, 'Bagel - Sesame Seed Presliced');
insert into public.brand_table (id, name) values (655, 'Juice - Orange, 341 Ml');
insert into public.brand_table (id, name) values (656, 'Beans - Fava Fresh');
insert into public.brand_table (id, name) values (657, 'Green Scrubbie Pad H.duty');
insert into public.brand_table (id, name) values (658, 'Wine - Magnotta, White');
insert into public.brand_table (id, name) values (659, 'Beer - Corona');
insert into public.brand_table (id, name) values (660, 'Pastry - Baked Cinnamon Stick');
insert into public.brand_table (id, name) values (661, 'Tomatoes - Roma');
insert into public.brand_table (id, name) values (662, 'Cheese - Sheep Milk');
insert into public.brand_table (id, name) values (663, 'Lettuce - Baby Salad Greens');
insert into public.brand_table (id, name) values (664, 'Flower - Potmums');
insert into public.brand_table (id, name) values (665, 'Stock - Veal, White');
insert into public.brand_table (id, name) values (666, 'Wine - White, Lindemans Bin 95');
insert into public.brand_table (id, name) values (667, 'Ice Cream - Turtles Stick Bar');
insert into public.brand_table (id, name) values (668, 'Kellogs Raisan Bran Bars');
insert into public.brand_table (id, name) values (669, 'Toamtoes 6x7 Select');
insert into public.brand_table (id, name) values (670, 'Beer - Upper Canada Light');
insert into public.brand_table (id, name) values (671, 'Wine - Coteaux Du Tricastin Ac');
insert into public.brand_table (id, name) values (672, 'Cup - 3.5oz, Foam');
insert into public.brand_table (id, name) values (673, 'Oil - Olive Bertolli');
insert into public.brand_table (id, name) values (674, 'Flour Dark Rye');
insert into public.brand_table (id, name) values (675, 'Ecolab - Hand Soap Form Antibac');
insert into public.brand_table (id, name) values (676, 'Wine - Alicanca Vinho Verde');
insert into public.brand_table (id, name) values (677, 'Coffee - Irish Cream');
insert into public.brand_table (id, name) values (678, 'Beans - Soya Bean');
insert into public.brand_table (id, name) values (679, 'Pails With Lids');
insert into public.brand_table (id, name) values (680, 'Turnip - Mini');
insert into public.brand_table (id, name) values (681, 'Bread - White, Sliced');
insert into public.brand_table (id, name) values (682, 'Peach - Halves');
insert into public.brand_table (id, name) values (683, 'Pail - 4l White, With Handle');
insert into public.brand_table (id, name) values (684, 'Beer - Paulaner Hefeweisse');
insert into public.brand_table (id, name) values (685, 'Puree - Pear');
insert into public.brand_table (id, name) values (686, 'Liqueur Banana, Ramazzotti');
insert into public.brand_table (id, name) values (687, 'Juice - Ocean Spray Cranberry');
insert into public.brand_table (id, name) values (688, 'Salmon - Atlantic, No Skin');
insert into public.brand_table (id, name) values (689, 'Cookies - Amaretto');
insert into public.brand_table (id, name) values (690, 'Cheese - Swiss');
insert into public.brand_table (id, name) values (691, 'Island Oasis - Magarita Mix');
insert into public.brand_table (id, name) values (692, 'Bread - Burger');
insert into public.brand_table (id, name) values (693, 'Wine - Stoneliegh Sauvignon');
insert into public.brand_table (id, name) values (694, 'Juice - Apple, 341 Ml');
insert into public.brand_table (id, name) values (695, 'Brandy - Orange, Mc Guiness');
insert into public.brand_table (id, name) values (696, 'Venison - Denver Leg Boneless');
insert into public.brand_table (id, name) values (697, 'Avocado');
insert into public.brand_table (id, name) values (698, 'Coffee - Irish Cream');
insert into public.brand_table (id, name) values (699, 'Crab - Imitation Flakes');
insert into public.brand_table (id, name) values (700, 'Compound - Orange');
insert into public.brand_table (id, name) values (701, 'Wine - Sawmill Creek Autumn');
insert into public.brand_table (id, name) values (702, 'Artichokes - Jerusalem');
insert into public.brand_table (id, name) values (703, 'V8 Splash Strawberry Banana');
insert into public.brand_table (id, name) values (704, 'Wine - White, Colubia Cresh');
insert into public.brand_table (id, name) values (705, 'Bread - Pita, Mini');
insert into public.brand_table (id, name) values (706, 'Shortbread - Cookie Crumbs');
insert into public.brand_table (id, name) values (707, 'Chilli Paste, Sambal Oelek');
insert into public.brand_table (id, name) values (708, 'Yeast - Fresh, Fleischman');
insert into public.brand_table (id, name) values (709, 'Clams - Canned');
insert into public.brand_table (id, name) values (710, 'French Pastry - Mini Chocolate');
insert into public.brand_table (id, name) values (711, 'Five Alive Citrus');
insert into public.brand_table (id, name) values (712, 'Corn Syrup');
insert into public.brand_table (id, name) values (713, 'Bacardi Raspberry');
insert into public.brand_table (id, name) values (714, 'Tart Shells - Savory, 4');
insert into public.brand_table (id, name) values (715, 'Bagelers - Cinn / Brown Sugar');
insert into public.brand_table (id, name) values (716, 'Flour - Pastry');
insert into public.brand_table (id, name) values (717, 'Tuna - Yellowfin');
insert into public.brand_table (id, name) values (718, 'Sobe - Liz Blizz');
insert into public.brand_table (id, name) values (719, 'Aspic - Clear');
insert into public.brand_table (id, name) values (720, 'Bread - Raisin Walnut Pull');
insert into public.brand_table (id, name) values (721, 'Flour - Buckwheat, Dark');
insert into public.brand_table (id, name) values (722, 'Bread - White Mini Epi');
insert into public.brand_table (id, name) values (723, 'Wine - Barbera Alba Doc 2001');
insert into public.brand_table (id, name) values (724, 'Pears - Bosc');
insert into public.brand_table (id, name) values (725, 'Tomatoes Tear Drop Yellow');
insert into public.brand_table (id, name) values (726, 'Wine - Tio Pepe Sherry Fino');
insert into public.brand_table (id, name) values (727, 'Wine - Montecillo Rioja Crianza');
insert into public.brand_table (id, name) values (728, 'Pepper - Red Thai');
insert into public.brand_table (id, name) values (729, 'Apple - Macintosh');
insert into public.brand_table (id, name) values (730, 'Aspic - Amber');
insert into public.brand_table (id, name) values (731, 'Chocolate - Dark');
insert into public.brand_table (id, name) values (732, 'Huck White Towels');
insert into public.brand_table (id, name) values (733, 'Basil - Primerba, Paste');
insert into public.brand_table (id, name) values (734, 'Nantucket Apple Juice');
insert into public.brand_table (id, name) values (735, 'Muffin - Mix - Mango Sour Cherry');
insert into public.brand_table (id, name) values (736, 'Alize Gold Passion');
insert into public.brand_table (id, name) values (737, 'Sprouts - Corn');
insert into public.brand_table (id, name) values (738, 'Brandy - Bar');
insert into public.brand_table (id, name) values (739, 'Island Oasis - Sweet And Sour Mix');
insert into public.brand_table (id, name) values (740, 'Tamarillo');
insert into public.brand_table (id, name) values (741, 'Irish Cream - Butterscotch');
insert into public.brand_table (id, name) values (742, 'Pepper - Chili Powder');
insert into public.brand_table (id, name) values (743, 'Sparkling Wine - Rose, Freixenet');
insert into public.brand_table (id, name) values (744, 'Wine - Toasted Head');
insert into public.brand_table (id, name) values (745, 'Wine - Tio Pepe Sherry Fino');
insert into public.brand_table (id, name) values (746, 'Clementine');
insert into public.brand_table (id, name) values (747, 'Ecolab - Ster Bac');
insert into public.brand_table (id, name) values (748, 'Olives - Nicoise');
insert into public.brand_table (id, name) values (749, 'Cookie Double Choco');
insert into public.brand_table (id, name) values (750, 'Beer - True North Strong Ale');
insert into public.brand_table (id, name) values (751, 'Wine - White, Chardonnay');
insert into public.brand_table (id, name) values (752, 'Beer - Upper Canada Lager');
insert into public.brand_table (id, name) values (753, 'Soup - Cream Of Potato / Leek');
insert into public.brand_table (id, name) values (754, 'Lemonade - Black Cherry, 591 Ml');
insert into public.brand_table (id, name) values (755, 'Soup - French Can Pea');
insert into public.brand_table (id, name) values (756, 'Cabbage - Savoy');
insert into public.brand_table (id, name) values (757, 'Wine - Vouvray Cuvee Domaine');
insert into public.brand_table (id, name) values (758, 'Wine - Semi Dry Riesling Vineland');
insert into public.brand_table (id, name) values (759, 'Pepper - Green');
insert into public.brand_table (id, name) values (760, 'Temperature Recording Station');
insert into public.brand_table (id, name) values (761, 'Broom - Corn');
insert into public.brand_table (id, name) values (762, 'Scallops - U - 10');
insert into public.brand_table (id, name) values (763, 'Muffin Mix - Lemon Cranberry');
insert into public.brand_table (id, name) values (764, 'Instant Coffee');
insert into public.brand_table (id, name) values (765, 'Carrots - Mini, Stem On');
insert into public.brand_table (id, name) values (766, 'Sugar - Brown');
insert into public.brand_table (id, name) values (767, 'Soda Water - Club Soda, 355 Ml');
insert into public.brand_table (id, name) values (768, 'Gelatine Leaves - Envelopes');
insert into public.brand_table (id, name) values (769, 'Lid - 0090 Clear');
insert into public.brand_table (id, name) values (770, 'Spinach - Spinach Leaf');
insert into public.brand_table (id, name) values (771, 'Ham - Cooked Bayonne Tinned');
insert into public.brand_table (id, name) values (772, 'Rice - 7 Grain Blend');
insert into public.brand_table (id, name) values (773, 'Pepper - Gypsy Pepper');
insert into public.brand_table (id, name) values (774, 'Grenadine');
insert into public.brand_table (id, name) values (775, 'Appetizer - Asian Shrimp Roll');
insert into public.brand_table (id, name) values (776, 'Pepsi - Diet, 355 Ml');
insert into public.brand_table (id, name) values (777, 'Wine - Riesling Dr. Pauly');
insert into public.brand_table (id, name) values (778, 'Salt And Pepper Mix - White');
insert into public.brand_table (id, name) values (779, 'Cheese - Shred Cheddar / Mozza');
insert into public.brand_table (id, name) values (780, 'Crackers - Trio');
insert into public.brand_table (id, name) values (781, 'Canada Dry');
insert into public.brand_table (id, name) values (782, 'Syrup - Monin - Passion Fruit');
insert into public.brand_table (id, name) values (783, 'Calypso - Strawberry Lemonade');
insert into public.brand_table (id, name) values (784, 'Cake - Pancake');
insert into public.brand_table (id, name) values (785, 'Sloe Gin - Mcguinness');
insert into public.brand_table (id, name) values (786, 'Extract - Vanilla,artificial');
insert into public.brand_table (id, name) values (787, 'Puree - Passion Fruit');
insert into public.brand_table (id, name) values (788, 'Beef - Diced');
insert into public.brand_table (id, name) values (789, 'Macaroons - Two Bite Choc');
insert into public.brand_table (id, name) values (790, 'Wine - Niagara Peninsula Vqa');
insert into public.brand_table (id, name) values (791, 'Bread - Malt');
insert into public.brand_table (id, name) values (792, 'Mcguinness - Blue Curacao');
insert into public.brand_table (id, name) values (793, 'Bread - Rolls, Corn');
insert into public.brand_table (id, name) values (794, 'Galliano');
insert into public.brand_table (id, name) values (795, 'Sauce - Gravy, Au Jus, Mix');
insert into public.brand_table (id, name) values (796, 'Tortillas - Flour, 8');
insert into public.brand_table (id, name) values (797, 'Beans - French');
insert into public.brand_table (id, name) values (798, 'Cookie Double Choco');
insert into public.brand_table (id, name) values (799, 'Chinese Foods - Pepper Beef');
insert into public.brand_table (id, name) values (800, 'Lemon Pepper');
insert into public.brand_table (id, name) values (801, 'Plate - Foam, Bread And Butter');
insert into public.brand_table (id, name) values (802, 'Mop Head - Cotton, 24 Oz');
insert into public.brand_table (id, name) values (803, 'Chicken - Leg / Back Attach');
insert into public.brand_table (id, name) values (804, 'Tomatoes');
insert into public.brand_table (id, name) values (805, 'Pork - Tenderloin, Frozen');
insert into public.brand_table (id, name) values (806, 'Capicola - Hot');
insert into public.brand_table (id, name) values (807, 'Pasta - Fettuccine, Egg, Fresh');
insert into public.brand_table (id, name) values (808, 'Coffee - Dark Roast');
insert into public.brand_table (id, name) values (809, 'Beef - Kobe Striploin');
insert into public.brand_table (id, name) values (810, 'Milkettes - 2%');
insert into public.brand_table (id, name) values (811, 'Muffin Mix - Raisin Bran');
insert into public.brand_table (id, name) values (812, 'Pasta - Cappellini, Dry');
insert into public.brand_table (id, name) values (813, 'Cheese - Manchego, Spanish');
insert into public.brand_table (id, name) values (814, 'Veal - Osso Bucco');
insert into public.brand_table (id, name) values (815, 'Chocolate Eclairs');
insert into public.brand_table (id, name) values (816, 'Lamb - Ground');
insert into public.brand_table (id, name) values (817, 'Pepper - Black, Whole');
insert into public.brand_table (id, name) values (818, 'Juice - Apple, 341 Ml');
insert into public.brand_table (id, name) values (819, 'Tuna - Yellowfin');
insert into public.brand_table (id, name) values (820, 'Bandage - Flexible Neon');
insert into public.brand_table (id, name) values (821, 'Wine - White, Pelee Island');
insert into public.brand_table (id, name) values (822, 'Cookies - Amaretto');
insert into public.brand_table (id, name) values (823, 'Nantucket Cranberry Juice');
insert into public.brand_table (id, name) values (824, 'Tortillas - Flour, 10');
insert into public.brand_table (id, name) values (825, 'The Pop Shoppe - Cream Soda');
insert into public.brand_table (id, name) values (826, 'Chinese Foods - Chicken');
insert into public.brand_table (id, name) values (827, 'Brownies - Two Bite, Chocolate');
insert into public.brand_table (id, name) values (828, 'Lotus Leaves');
insert into public.brand_table (id, name) values (829, 'Salad Dressing');
insert into public.brand_table (id, name) values (830, 'Bread - Crumbs, Bulk');
insert into public.brand_table (id, name) values (831, 'Dish Towel');
insert into public.brand_table (id, name) values (832, 'Crab Brie In Phyllo');
insert into public.brand_table (id, name) values (833, 'Nut - Walnut, Pieces');
insert into public.brand_table (id, name) values (834, 'Turkey Leg With Drum And Thigh');
insert into public.brand_table (id, name) values (835, 'Parsley - Dried');
insert into public.brand_table (id, name) values (836, 'Beer - Creemore');
insert into public.brand_table (id, name) values (837, 'Ecolab - Hobart Upr Prewash Arm');
insert into public.brand_table (id, name) values (838, 'Bamboo Shoots - Sliced');
insert into public.brand_table (id, name) values (839, 'Sobe - Berry Energy');
insert into public.brand_table (id, name) values (840, 'Foil Wrap');
insert into public.brand_table (id, name) values (841, 'Coffee - Decafenated');
insert into public.brand_table (id, name) values (842, 'Pears - Bosc');
insert into public.brand_table (id, name) values (843, 'Tea - Camomele');
insert into public.brand_table (id, name) values (844, 'Oysters - Smoked');
insert into public.brand_table (id, name) values (845, 'Lettuce - Curly Endive');
insert into public.brand_table (id, name) values (846, 'Crab - Dungeness, Whole');
insert into public.brand_table (id, name) values (847, 'Maple Syrup');
insert into public.brand_table (id, name) values (848, 'Kohlrabi');
insert into public.brand_table (id, name) values (849, 'Spice - Onion Powder Granulated');
insert into public.brand_table (id, name) values (850, 'Pepper - Green, Chili');
insert into public.brand_table (id, name) values (851, 'C - Plus, Orange');
insert into public.brand_table (id, name) values (852, 'Snapple - Iced Tea Peach');
insert into public.brand_table (id, name) values (853, 'Pasta - Canelloni, Single Serve');
insert into public.brand_table (id, name) values (854, 'Soup - Campbells - Chicken Noodle');
insert into public.brand_table (id, name) values (855, 'Wine - Sauvignon Blanc');
insert into public.brand_table (id, name) values (856, 'Plate Foam Laminated 9in Blk');
insert into public.brand_table (id, name) values (857, 'Juice - Apple 284ml');
insert into public.brand_table (id, name) values (858, 'Broom - Corn');
insert into public.brand_table (id, name) values (859, 'Flower - Leather Leaf Fern');
insert into public.brand_table (id, name) values (860, 'Potatoes - Yukon Gold, 80 Ct');
insert into public.brand_table (id, name) values (861, 'Dried Apple');
insert into public.brand_table (id, name) values (862, 'Bread - White Epi Baguette');
insert into public.brand_table (id, name) values (863, 'Table Cloth 62x114 Colour');
insert into public.brand_table (id, name) values (864, 'Wine - Segura Viudas Aria Brut');
insert into public.brand_table (id, name) values (865, 'Wine - Prem Select Charddonany');
insert into public.brand_table (id, name) values (866, 'Carbonated Water - Cherry');
insert into public.brand_table (id, name) values (867, 'Tea - Grapefruit Green Tea');
insert into public.brand_table (id, name) values (868, 'Salmon - Whole, 4 - 6 Pounds');
insert into public.brand_table (id, name) values (869, 'Tomatoes - Hot House');
insert into public.brand_table (id, name) values (870, 'Longos - Penne With Pesto');
insert into public.brand_table (id, name) values (871, 'Steampan - Half Size Shallow');
insert into public.brand_table (id, name) values (872, 'Iced Tea Concentrate');
insert into public.brand_table (id, name) values (873, 'Soda Water - Club Soda, 355 Ml');
insert into public.brand_table (id, name) values (874, 'Cheese - Perron Cheddar');
insert into public.brand_table (id, name) values (875, 'Arctic Char - Fillets');
insert into public.brand_table (id, name) values (876, 'Banana');
insert into public.brand_table (id, name) values (877, 'Cup Translucent 9 Oz');
insert into public.brand_table (id, name) values (878, 'Carbonated Water - Wildberry');
insert into public.brand_table (id, name) values (879, 'Flour - Teff');
insert into public.brand_table (id, name) values (880, 'Sauce Bbq Smokey');
insert into public.brand_table (id, name) values (881, 'Pie Box - Cello Window 2.5');
insert into public.brand_table (id, name) values (882, 'Pasta - Linguini, Dry');
insert into public.brand_table (id, name) values (883, 'Toothpick Frilled');
insert into public.brand_table (id, name) values (884, 'Pepper - Paprika, Spanish');
insert into public.brand_table (id, name) values (885, 'Crackers Cheez It');
insert into public.brand_table (id, name) values (886, 'Wine - Coteaux Du Tricastin Ac');
insert into public.brand_table (id, name) values (887, 'Crab - Dungeness, Whole, live');
insert into public.brand_table (id, name) values (888, 'Southern Comfort');
insert into public.brand_table (id, name) values (889, 'Wine - Fontanafredda Barolo');
insert into public.brand_table (id, name) values (890, 'Mushroom - Porcini Frozen');
insert into public.brand_table (id, name) values (891, 'Pastry - Choclate Baked');
insert into public.brand_table (id, name) values (892, 'Towels - Paper / Kraft');
insert into public.brand_table (id, name) values (893, 'Salmon Steak - Cohoe 6 Oz');
insert into public.brand_table (id, name) values (894, 'Tart Shells - Sweet, 3');
insert into public.brand_table (id, name) values (895, 'Compound - Mocha');
insert into public.brand_table (id, name) values (896, 'Snails - Large Canned');
insert into public.brand_table (id, name) values (897, 'Sauce - Caesar Dressing');
insert into public.brand_table (id, name) values (898, 'Nestea - Ice Tea, Diet');
insert into public.brand_table (id, name) values (899, 'Hersey Shakes');
insert into public.brand_table (id, name) values (900, 'Creme De Menthe Green');
insert into public.brand_table (id, name) values (901, 'Wine - Rosso Toscano Igt');
insert into public.brand_table (id, name) values (902, 'French Pastry - Mini Chocolate');
insert into public.brand_table (id, name) values (903, 'Jam - Strawberry, 20 Ml Jar');
insert into public.brand_table (id, name) values (904, 'Cookie Choc');
insert into public.brand_table (id, name) values (905, 'Pur Source');
insert into public.brand_table (id, name) values (906, 'Cookies - Fortune');
insert into public.brand_table (id, name) values (907, 'Evaporated Milk - Skim');
insert into public.brand_table (id, name) values (908, 'Wine - Two Oceans Sauvignon');
insert into public.brand_table (id, name) values (909, 'Soup - Tomato Mush. Florentine');
insert into public.brand_table (id, name) values (910, 'Bread - Burger');
insert into public.brand_table (id, name) values (911, 'Bread - Roll, Calabrese');
insert into public.brand_table (id, name) values (912, 'Sauce - Soy Low Sodium - 3.87l');
insert into public.brand_table (id, name) values (913, 'Sauce - Black Current, Dry Mix');
insert into public.brand_table (id, name) values (914, 'Pasta - Ravioli');
insert into public.brand_table (id, name) values (915, 'Cheese - Havarti, Roasted Garlic');
insert into public.brand_table (id, name) values (916, 'Mints - Striped Red');
insert into public.brand_table (id, name) values (917, 'Trueblue - Blueberry');
insert into public.brand_table (id, name) values (918, 'V8 Pet');
insert into public.brand_table (id, name) values (919, 'Tea - Herbal Orange Spice');
insert into public.brand_table (id, name) values (920, 'Nantucket - Kiwi Berry Cktl.');
insert into public.brand_table (id, name) values (921, 'Magnotta Bel Paese Red');
insert into public.brand_table (id, name) values (922, 'Pasta - Penne, Lisce, Dry');
insert into public.brand_table (id, name) values (923, 'Coke - Classic, 355 Ml');
insert into public.brand_table (id, name) values (924, 'Tomato - Peeled Italian Canned');
insert into public.brand_table (id, name) values (925, 'Juice - Cranberry, 341 Ml');
insert into public.brand_table (id, name) values (926, 'Ecolab - Medallion');
insert into public.brand_table (id, name) values (927, 'Beef - Rib Roast, Cap On');
insert into public.brand_table (id, name) values (928, 'Beef - Tenderloin');
insert into public.brand_table (id, name) values (929, 'Veal - Round, Eye Of');
insert into public.brand_table (id, name) values (930, 'Tea - Herbal Orange Spice');
insert into public.brand_table (id, name) values (931, 'Energy Drink');
insert into public.brand_table (id, name) values (932, 'Yogurt - Assorted Pack');
insert into public.brand_table (id, name) values (933, 'Lid - 0090 Clear');
insert into public.brand_table (id, name) values (934, 'Ecolab - Hobart Upr Prewash Arm');
insert into public.brand_table (id, name) values (935, 'Triple Sec - Mcguinness');
insert into public.brand_table (id, name) values (936, 'Wine - Alicanca Vinho Verde');
insert into public.brand_table (id, name) values (937, 'Bread - Corn Muffaleta Onion');
insert into public.brand_table (id, name) values (938, 'Sauce - Oyster');
insert into public.brand_table (id, name) values (939, 'Fruit Mix - Light');
insert into public.brand_table (id, name) values (940, 'Longos - Grilled Veg Sandwiches');
insert into public.brand_table (id, name) values (941, 'Sauce - Thousand Island');
insert into public.brand_table (id, name) values (942, 'Wine - Baron De Rothschild');
insert into public.brand_table (id, name) values (943, 'Bar Special K');
insert into public.brand_table (id, name) values (944, 'Kirsch - Schloss');
insert into public.brand_table (id, name) values (945, 'Cream Of Tartar');
insert into public.brand_table (id, name) values (946, 'Sauce - Chili');
insert into public.brand_table (id, name) values (947, 'Muffin Puck Ww Carrot');
insert into public.brand_table (id, name) values (948, 'Brandy - Orange, Mc Guiness');
insert into public.brand_table (id, name) values (949, 'Ranchero - Primerba, Paste');
insert into public.brand_table (id, name) values (950, 'Mackerel Whole Fresh');
insert into public.brand_table (id, name) values (951, 'Sugar - Brown, Individual');
insert into public.brand_table (id, name) values (952, 'Cream - 10%');
insert into public.brand_table (id, name) values (953, 'Pork - Side Ribs');
insert into public.brand_table (id, name) values (954, 'Mushroom - Porcini, Dry');
insert into public.brand_table (id, name) values (955, 'Wine - Rioja Campo Viejo');
insert into public.brand_table (id, name) values (956, 'Pork - Loin, Center Cut');
insert into public.brand_table (id, name) values (957, 'Beans - Black Bean, Preserved');
insert into public.brand_table (id, name) values (958, 'Paper Cocktail Umberlla 80 - 180');
insert into public.brand_table (id, name) values (959, 'Pears - Bartlett');
insert into public.brand_table (id, name) values (960, 'Snapple Lemon Tea');
insert into public.brand_table (id, name) values (961, 'Carbonated Water - Peach');
insert into public.brand_table (id, name) values (962, 'Curry Powder');
insert into public.brand_table (id, name) values (963, 'Rice - Wild');
insert into public.brand_table (id, name) values (964, 'Cucumber - English');
insert into public.brand_table (id, name) values (965, 'Tea - Grapefruit Green Tea');
insert into public.brand_table (id, name) values (966, 'Cocktail Napkin Blue');
insert into public.brand_table (id, name) values (967, 'Cheese - Sheep Milk');
insert into public.brand_table (id, name) values (968, 'Lentils - Green Le Puy');
insert into public.brand_table (id, name) values (969, 'Bag Clear 10 Lb');
insert into public.brand_table (id, name) values (970, 'Tray - Foam, Square 4 - S');
insert into public.brand_table (id, name) values (971, 'Turnip - White, Organic');
insert into public.brand_table (id, name) values (972, 'Mushroom - Morels, Dry');
insert into public.brand_table (id, name) values (973, 'Spice - Chili Powder Mexican');
insert into public.brand_table (id, name) values (974, 'Longos - Chicken Curried');
insert into public.brand_table (id, name) values (975, 'Aspic - Light');
insert into public.brand_table (id, name) values (976, 'Plums - Red');
insert into public.brand_table (id, name) values (977, 'Caviar - Salmon');
insert into public.brand_table (id, name) values (978, 'Clementine');
insert into public.brand_table (id, name) values (979, 'Anchovy Fillets');
insert into public.brand_table (id, name) values (980, 'Sauce - Soya, Dark');
insert into public.brand_table (id, name) values (981, 'Bread - Focaccia Quarter');
insert into public.brand_table (id, name) values (982, 'Curry Powder');
insert into public.brand_table (id, name) values (983, 'Pasta - Cheese / Spinach Bauletti');
insert into public.brand_table (id, name) values (984, 'Mushroom - Porcini, Dry');
insert into public.brand_table (id, name) values (985, 'Chilli Paste, Sambal Oelek');
insert into public.brand_table (id, name) values (986, 'Petite Baguette');
insert into public.brand_table (id, name) values (987, 'Cheese - Victor Et Berthold');
insert into public.brand_table (id, name) values (988, 'Pork - Ham, Virginia');
insert into public.brand_table (id, name) values (989, 'Pasta - Ravioli');
insert into public.brand_table (id, name) values (990, 'Nut - Almond, Blanched, Sliced');
insert into public.brand_table (id, name) values (991, 'Spinach - Baby');
insert into public.brand_table (id, name) values (992, 'Olives - Black, Pitted');
insert into public.brand_table (id, name) values (993, 'Pork - Bacon Cooked Slcd');
insert into public.brand_table (id, name) values (994, '7up Diet, 355 Ml');
insert into public.brand_table (id, name) values (995, 'Cognac - Courvaisier');
insert into public.brand_table (id, name) values (996, 'Pickerel - Fillets');
insert into public.brand_table (id, name) values (997, 'Fennel - Seeds');
insert into public.brand_table (id, name) values (998, 'Broom - Corn');
insert into public.brand_table (id, name) values (999, 'Zucchini - Mini, Green');
insert into public.brand_table (id, name) values (1000, 'Jam - Blackberry, 20 Ml Jar');
