insert into public.measurement_table (name) values ('teaspoon (tsp)');
insert into public.measurement_table (name) values ('tablespoon (tbsp)');
insert into public.measurement_table (name) values ('fluid ounce (fl oz)');
insert into public.measurement_table (name) values ('gill');
insert into public.measurement_table (name) values ('cup (c)');
insert into public.measurement_table (name) values ('pint (pt)');
insert into public.measurement_table (name) values ('quart (qt)');
insert into public.measurement_table (name) values ('gallon (gal)');
insert into public.measurement_table (name) values ('milliliter (mL)');
insert into public.measurement_table (name) values ('liter (L)');
insert into public.measurement_table (name) values ('deciliter(dL)');
insert into public.measurement_table (name) values ('pound (lb)');
insert into public.measurement_table (name) values ('ounce (oz)');
insert into public.measurement_table (name) values ('mg (milligram)');
insert into public.measurement_table (name) values ('g (gram)');
insert into public.measurement_table (name) values ('kilogram (kg)');
insert into public.measurement_table (name) values ('millimeter (mm)');
insert into public.measurement_table (name) values ('centimeter (cm)');
insert into public.measurement_table (name) values ('meter (m)');
insert into public.measurement_table (name) values ('inch (in)');
insert into public.measurement_table (name) values ('unit');